import { createHash, randomBytes, randomUUID } from "node:crypto";
import { demoViewer, getDemoCalendarItems, getDemoScheduleVersion, replaceDemoCalendarItems } from "@/lib/demo-data";
import { findMeetingOptions, interpretMeetingCommand } from "@/lib/meetings/engine";
import type { CalendarItem, Viewer } from "@/lib/types";
import type { MeetingCard, MeetingOption, MeetingRecord } from "@/lib/meetings/types";
import { AppError } from "@/lib/http";

export const CHLOE_ID="22222222-2222-4222-8222-222222222222";
export const chloeViewer:Viewer={id:CHLOE_ID,email:"chloe@kairos.app",fullName:"Chloe",username:"chloe",timezone:"Asia/Manila",activeStart:"07:00",activeEnd:"22:30",travelBufferMinutes:15,avatarUrl:null,preview:true,scheduleVersion:1};
type BookingMeta={expiresAt:string;revokedAt:string|null};
type State={meetings:Map<string,MeetingRecord>;chloeCalendar:CalendarItem[];chloeVersion:number;bookingMeta:Map<string,BookingMeta>};
const root=globalThis as typeof globalThis&{__kairosMeetingState?:State};
function at(day:number,hour:number,minute=0){const base=new Date();base.setDate(base.getDate()+day);base.setHours(hour,minute,0,0);return base.toISOString();}
function initial():State{return{meetings:new Map(),bookingMeta:new Map(),chloeVersion:1,chloeCalendar:[{id:"chloe-client",userId:CHLOE_ID,type:"event",title:"Client Review",description:null,startAt:at(1,10),endAt:at(1,11),dueAt:null,timezone:"Asia/Manila",priority:5,flexibility:"fixed",earliestStart:null,latestEnd:null,normalDurationMinutes:60,minimumDurationMinutes:60,minimumChunkMinutes:null,canShorten:false,canSplit:false,canSkip:false,locationLabel:"Online",relatedDeadlineId:null,dependencyIds:[],category:"Meeting",reminderMinutes:10,status:"scheduled",version:1}]};}
function state(){return root.__kairosMeetingState??=initial();}
export function resetPreviewMeetings(){root.__kairosMeetingState=initial();}
export function getPreviewChloeCalendar(){return structuredClone(state().chloeCalendar);}
export function previewActor(value:string|null){return value?.toLowerCase()==="chloe"?chloeViewer:{...demoViewer,scheduleVersion:getDemoScheduleVersion()};}
function card(record:MeetingRecord,actorId:string):MeetingCard{const participant=record.participants.find((entry)=>entry.userId===actorId);return{...structuredClone(record),actorId,actorRole:participant?.role??"recipient",bookingPath:record.bookingToken?`/book/${record.bookingToken}`:null,bookingToken:undefined,baseScheduleVersions:undefined} as unknown as MeetingCard;}
export function listPreviewMeetings(actorId:string){return[...state().meetings.values()].filter((meeting)=>meeting.participants.some((participant)=>participant.userId===actorId)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map((meeting)=>card(meeting,actorId));}
export function createPreviewMeeting(command:string,actor=demoViewer){const intent=interpretMeetingCommand(command);if(intent.ambiguity)return{status:"needs_input" as const,question:intent.ambiguity};const recipient=intent.participantEmail?{userId:null,email:intent.participantEmail,name:intent.participant,role:"recipient" as const}:{userId:CHLOE_ID,email:chloeViewer.email,name:chloeViewer.fullName,role:"recipient" as const};const options=findMeetingOptions(actor,chloeViewer,getDemoCalendarItems(),recipient.userId?state().chloeCalendar:[],intent.rangeStart,intent.rangeEnd,intent.durationMinutes);if(!options.length)return{status:"impossible" as const,error:"No shared opening fits the requested range and active hours."};const token=recipient.userId?null:randomBytes(24).toString("base64url"),now=new Date().toISOString();const meeting:MeetingRecord={id:randomUUID(),title:intent.title,state:intent.mode==="send"?"options_sent":"draft",createdBy:actor.id,participants:[{userId:actor.id,email:actor.email,name:actor.fullName,role:"organizer"},recipient],durationMinutes:intent.durationMinutes,rangeStart:intent.rangeStart,rangeEnd:intent.rangeEnd,timezone:actor.timezone,options,selectedOptionId:null,activeResponder:intent.mode==="send"?(recipient.userId??recipient.email):actor.id,version:1,createdAt:now,updatedAt:now,deliveries:intent.mode==="send"?[recipient.userId?{channel:"in_app",status:"delivered",label:"Delivered in Kairos"}:{channel:"email",status:"simulated",label:"Simulated email delivery"}]:[],bookingToken:token,baseScheduleVersions:{[actor.id]:getDemoScheduleVersion(),[CHLOE_ID]:state().chloeVersion}};state().meetings.set(meeting.id,meeting);if(token)state().bookingMeta.set(token,{expiresAt:new Date(Date.now()+7*24*60*60_000).toISOString(),revokedAt:null});return{status:"meeting" as const,meeting:card(meeting,actor.id)};}
function addEvent(calendar:CalendarItem[],userId:string,meeting:MeetingRecord,option:MeetingOption){return[...calendar,{id:randomUUID(),userId,type:"event" as const,title:meeting.title,description:"Confirmed through Kairos meeting coordination",startAt:option.startAt,endAt:option.endAt,dueAt:null,timezone:meeting.timezone,priority:4,flexibility:"fixed" as const,earliestStart:null,latestEnd:null,normalDurationMinutes:meeting.durationMinutes,minimumDurationMinutes:meeting.durationMinutes,minimumChunkMinutes:null,canShorten:false,canSplit:false,canSkip:false,locationLabel:"Online",relatedDeadlineId:null,dependencyIds:[],category:"Meeting",reminderMinutes:10,status:"scheduled" as const,version:1}];}
export function actOnPreviewMeeting(id:string,actorId:string,action:string,payload:{optionId?:string;counterStart?:string}={}){const meeting=state().meetings.get(id);if(!meeting)throw new AppError("Meeting request not found.");const actor=meeting.participants.find((participant)=>participant.userId===actorId);if(!actor)throw new AppError("You do not have access to this request.");if(["confirmed","declined","expired","cancelled"].includes(meeting.state))throw new AppError("This request is already closed.");
  if(action==="send"&&actor.role==="organizer"&&meeting.state==="draft"){meeting.state="options_sent";meeting.activeResponder=meeting.participants.find((p)=>p.role==="recipient")?.userId??null;meeting.deliveries.push({channel:"in_app",status:"delivered",label:"Delivered in Kairos"});}
  else if(action==="accept"&&actor.role==="recipient"&&meeting.state==="options_sent"){const option=meeting.options.find((entry)=>entry.id===payload.optionId);if(!option)throw new AppError("Choose a current meeting option.");meeting.selectedOptionId=option.id;meeting.state="awaiting_sender_confirmation";meeting.activeResponder=meeting.createdBy;}
  else if(action==="counter"&&actor.role==="recipient"&&meeting.state==="options_sent"){const start=new Date(payload.counterStart??"");if(!Number.isFinite(start.getTime())||start<new Date(meeting.rangeStart)||start>new Date(meeting.rangeEnd))throw new AppError("Choose a counteroffer inside the requested range.");const option:MeetingOption={id:randomUUID(),startAt:start.toISOString(),endAt:new Date(start.getTime()+meeting.durationMinutes*60_000).toISOString(),label:new Intl.DateTimeFormat("en-US",{weekday:"short",hour:"numeric",minute:"2-digit",timeZone:meeting.timezone}).format(start),reason:"Recipient counteroffer",source:"counter"};meeting.options=[...meeting.options,option];meeting.selectedOptionId=option.id;meeting.state="awaiting_sender_confirmation";meeting.activeResponder=meeting.createdBy;}
  else if(action==="decline"&&actor.role==="recipient"&&meeting.state==="options_sent"){meeting.state="declined";meeting.activeResponder=null;}
  else if(action==="confirm"&&actor.role==="organizer"&&meeting.state==="awaiting_sender_confirmation"){const option=meeting.options.find((entry)=>entry.id===meeting.selectedOptionId);if(!option)throw new AppError("The selected option is missing.");const includesChloe=meeting.participants.some((participant)=>participant.userId===CHLOE_ID);if(getDemoScheduleVersion()!==meeting.baseScheduleVersions[demoViewer.id]||(includesChloe&&state().chloeVersion!==meeting.baseScheduleVersions[CHLOE_ID]))throw new AppError("A participant's schedule changed. Refresh the meeting options.");if(!replaceDemoCalendarItems(addEvent(getDemoCalendarItems(),demoViewer.id,meeting,option),meeting.baseScheduleVersions[demoViewer.id]))throw new AppError("The organizer's schedule changed.");if(includesChloe){state().chloeCalendar=addEvent(state().chloeCalendar,CHLOE_ID,meeting,option);state().chloeVersion++;}meeting.state="confirmed";meeting.activeResponder=null;}
  else if(action==="cancel"&&actor.role==="organizer"){meeting.state="cancelled";meeting.activeResponder=null;}
  else throw new AppError("That meeting transition is not allowed right now.");
  meeting.version++;meeting.updatedAt=new Date().toISOString();return card(meeting,actorId);
}
function digest(token:string){return createHash("sha256").update(token).digest("hex");}
function validBooking(token:string){const meta=state().bookingMeta.get(token);return Boolean(meta&&!meta.revokedAt&&new Date(meta.expiresAt)>new Date());}
export function expirePreviewBooking(token:string){const meta=state().bookingMeta.get(token);if(meta)meta.expiresAt=new Date(0).toISOString();}
export function revokePreviewBooking(token:string){const meta=state().bookingMeta.get(token);if(meta)meta.revokedAt=new Date().toISOString();}
export function getPreviewBooking(token:string){if(!validBooking(token))return null;const meeting=[...state().meetings.values()].find((entry)=>entry.bookingToken&&digest(entry.bookingToken)===digest(token));if(!meeting)return null;return{id:meeting.id,title:meeting.title,state:meeting.state,durationMinutes:meeting.durationMinutes,timezone:meeting.timezone,options:meeting.options,selectedOptionId:meeting.selectedOptionId,organizer:meeting.participants.find((p)=>p.role==="organizer")?.name??"Organizer"};}
export function actOnPreviewBooking(token:string,action:string,payload:{optionId?:string;counterStart?:string}){if(!validBooking(token))throw new AppError("This booking link is invalid, expired, or revoked.");const meeting=[...state().meetings.values()].find((entry)=>entry.bookingToken===token);if(!meeting)throw new AppError("This booking link is invalid, expired, or revoked.");if(meeting.state!=="options_sent")throw new AppError("This booking link is no longer awaiting a response.");const recipient=meeting.participants.find((p)=>p.role==="recipient")!;const temporaryId=recipient.userId??`external:${recipient.email}`;recipient.userId=temporaryId;try{return actOnPreviewMeeting(meeting.id,temporaryId,action,payload);}finally{recipient.userId=null;}}
