import "server-only";
import { createHash, randomBytes } from "node:crypto";
import { getCalendarItems, getViewer } from "@/lib/data";
import { mapCalendarRow } from "@/lib/demo-data";
import { isSupabaseConfigured } from "@/lib/env";
import { findMeetingOptions, interpretMeetingCommand } from "@/lib/meetings/engine";
import { actOnPreviewMeeting, createPreviewMeeting, listPreviewMeetings, previewActor } from "@/lib/meetings/preview-store";
import type { MeetingCard, MeetingDelivery, MeetingOption, MeetingParticipant, MeetingState } from "@/lib/meetings/types";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { AppError } from "@/lib/http";

export async function meetingActor(request:Request){return isSupabaseConfigured()?getViewer():previewActor(request.headers.get("x-demo-user"));}
// meeting_options is reachable through two foreign keys (meeting_id and the
// meeting's selected_option_id), so the embed must name the one it should follow.
const MEETING_SELECT="*,meeting_participants(user_id,email,name,role),meeting_options!meeting_options_meeting_id_fkey(id,start_at,end_at,label,reason,source),simulated_deliveries(channel,status)";
type ParticipantRow={user_id:string|null;email:string|null;name:string;role:MeetingParticipant["role"]};
type OptionRow={id:string;start_at:string;end_at:string;label:string;reason:string;source:MeetingOption["source"]};
type MeetingRow={id:string;title:string;state:MeetingState;created_by:string;duration_minutes:number;range_start:string;range_end:string;timezone:string;selected_option_id:string|null;active_responder:string|null;version:number;created_at:string;updated_at:string;meeting_participants?:ParticipantRow[];meeting_options?:OptionRow[];simulated_deliveries?:Array<{channel:MeetingDelivery["channel"]}>};
function mapMeetingRow(meeting:MeetingRow,actorId:string,bookingPath:string|null=null):MeetingCard{const participants=meeting.meeting_participants??[],options=[...(meeting.meeting_options??[])].sort((a,b)=>a.start_at.localeCompare(b.start_at)),deliveries=meeting.simulated_deliveries??[];const actor=participants.find((participant)=>participant.user_id===actorId);if(!actor)throw new AppError("You do not have access to this meeting.");return{id:meeting.id,title:meeting.title,state:meeting.state,createdBy:meeting.created_by,participants:participants.map((participant)=>({userId:participant.user_id,email:participant.email,name:participant.name,role:participant.role})) as MeetingParticipant[],durationMinutes:meeting.duration_minutes,rangeStart:meeting.range_start,rangeEnd:meeting.range_end,timezone:meeting.timezone,options:options.map((option)=>({id:option.id,startAt:option.start_at,endAt:option.end_at,label:option.label,reason:option.reason,source:option.source})),selectedOptionId:meeting.selected_option_id,activeResponder:meeting.active_responder,version:meeting.version,createdAt:meeting.created_at,updatedAt:meeting.updated_at,deliveries:deliveries.map((delivery)=>({channel:delivery.channel,status:"simulated",label:`Simulated ${delivery.channel} delivery`})),actorId,actorRole:actor.role,bookingPath};}
async function realMeetingCard(id:string,actorId:string,bookingPath:string|null=null):Promise<MeetingCard>{const admin=createAdminSupabaseClient();const{data:meeting,error}=await admin.from("meeting_requests").select(MEETING_SELECT).eq("id",id).single();if(error||!meeting)throw new AppError("Meeting request not found.");return mapMeetingRow(meeting as MeetingRow,actorId,bookingPath);}
export async function listMeetings(request:Request){const actor=await meetingActor(request);if(!isSupabaseConfigured())return listPreviewMeetings(actor.id);const admin=createAdminSupabaseClient();const {data}=await admin.from("meeting_participants").select("meeting_id").eq("user_id",actor.id);const ids=(data??[]).map((entry)=>entry.meeting_id);if(!ids.length)return[];
// One embedded read instead of four queries per meeting.
const{data:meetings}=await admin.from("meeting_requests").select(MEETING_SELECT).in("id",ids).order("created_at",{ascending:false});return((meetings??[]) as MeetingRow[]).map((meeting)=>mapMeetingRow(meeting,actor.id));}
export async function createMeeting(command:string,request:Request){const actor=await meetingActor(request);if(!isSupabaseConfigured())return createPreviewMeeting(command,actor);const intent=interpretMeetingCommand(command);if(intent.ambiguity)return{status:"needs_input" as const,question:intent.ambiguity};const admin=createAdminSupabaseClient();const[{data:profiles},{data:connections}]=await Promise.all([admin.from("profiles").select("id,email,full_name,username,timezone,active_start,active_end,schedule_version").limit(100),admin.from("connections").select("requester_id,addressee_id").eq("status","accepted").or(`requester_id.eq.${actor.id},addressee_id.eq.${actor.id}`)]);const friendIds=new Set((connections??[]).map((connection)=>connection.requester_id===actor.id?connection.addressee_id:connection.requester_id)),normalized=intent.participant.toLowerCase(),recipient=intent.participantEmail?null:(profiles??[]).find((profile)=>friendIds.has(profile.id)&&[profile.email,profile.full_name,profile.username].some((value:string)=>value?.toLowerCase()===normalized||value?.toLowerCase().includes(normalized)));
  if(!recipient&&!intent.participantEmail)return{status:"needs_input" as const,question:"I could not find that Kairos connection. Use Chloe or enter a guest email address."};
  if(recipient){const{data:permission}=await admin.from("schedule_permissions").select("scope").eq("owner_id",recipient.id).eq("grantee_id",actor.id).in("scope",["free_busy","categories"]).maybeSingle();if(!permission)return{status:"needs_input" as const,question:`${recipient.full_name} must allow you to use their free/busy time. They can enable it beside your name in Inbox.`};}
  // Only scheduled, timed items inside the requested range can create a conflict.
  const participantCalendar=recipient?(await admin.from("calendar_items").select("*").eq("user_id",recipient.id).eq("status","scheduled").not("start_at","is",null).lt("start_at",intent.rangeEnd).gt("end_at",intent.rangeStart)).data?.map((row)=>mapCalendarRow(row))??[]:[];
  const options=findMeetingOptions(actor,{timezone:recipient?.timezone??actor.timezone,activeStart:recipient?.active_start??"09:00",activeEnd:recipient?.active_end??"18:00"},await getCalendarItems(),participantCalendar,intent.rangeStart,intent.rangeEnd,intent.durationMinutes);if(!options.length)return{status:"impossible" as const,error:"No shared opening fits the requested range and active hours."};
  const token=intent.participantEmail?randomBytes(24).toString("base64url"):null,tokenHash=token?createHash("sha256").update(token).digest("hex"):null;const supabase=await createServerSupabaseClient();const {data:id,error}=await supabase.rpc("create_meeting_request",{p_title:intent.title,p_duration:intent.durationMinutes,p_range_start:intent.rangeStart,p_range_end:intent.rangeEnd,p_timezone:actor.timezone,p_recipient_user:recipient?.id??null,p_recipient_email:intent.participantEmail,p_recipient_name:recipient?.full_name??intent.participant,p_send:intent.mode==="send",p_options:options,p_token_hash:tokenHash,p_token_expires:token?new Date(Date.now()+7*24*60*60_000).toISOString():null});if(error)throw new AppError("Kairos could not create this meeting request safely.");return{status:"meeting" as const,meeting:await realMeetingCard(id,actor.id,token?`/book/${token}`:null)};
}
export async function actOnMeeting(id:string,action:string,payload:{optionId?:string;counterStart?:string},request:Request){const actor=await meetingActor(request);if(!isSupabaseConfigured())return actOnPreviewMeeting(id,actor.id,action,payload);const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc("respond_to_meeting",{p_meeting_id:id,p_action:action,p_option_id:payload.optionId??null,p_counter_start:payload.counterStart??null});if(error)throw new AppError(/changed|conflict/i.test(error.message)?"A participant's schedule changed. Generate fresh options.":"That meeting response is no longer valid.");return realMeetingCard(id,actor.id);}
