import "server-only";
import { createHash, randomBytes } from "node:crypto";
import { getCalendarItems, getViewer } from "@/lib/data";
import { mapCalendarRow } from "@/lib/demo-data";
import { isSupabaseConfigured } from "@/lib/env";
import { findMeetingOptions, interpretMeetingCommand } from "@/lib/meetings/engine";
import { actOnPreviewMeeting, createPreviewMeeting, listPreviewMeetings, previewActor } from "@/lib/meetings/preview-store";
import type { MeetingCard, MeetingParticipant } from "@/lib/meetings/types";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export async function meetingActor(request:Request){return isSupabaseConfigured()?getViewer():previewActor(request.headers.get("x-demo-user"));}
async function realMeetingCard(id:string,actorId:string,bookingPath:string|null=null):Promise<MeetingCard>{const admin=createAdminSupabaseClient();const [{data:meeting,error},{data:participants},{data:options},{data:deliveries}]=await Promise.all([admin.from("meeting_requests").select("*").eq("id",id).single(),admin.from("meeting_participants").select("user_id,email,name,role").eq("meeting_id",id),admin.from("meeting_options").select("id,start_at,end_at,label,reason,source").eq("meeting_id",id).order("start_at"),admin.from("simulated_deliveries").select("channel,status").eq("meeting_id",id)]);if(error||!meeting)throw new Error("Meeting request not found.");const actor=(participants??[]).find((participant)=>participant.user_id===actorId);if(!actor)throw new Error("You do not have access to this meeting.");return{id:meeting.id,title:meeting.title,state:meeting.state,createdBy:meeting.created_by,participants:(participants??[]).map((participant)=>({userId:participant.user_id,email:participant.email,name:participant.name,role:participant.role})) as MeetingParticipant[],durationMinutes:meeting.duration_minutes,rangeStart:meeting.range_start,rangeEnd:meeting.range_end,timezone:meeting.timezone,options:(options??[]).map((option)=>({id:option.id,startAt:option.start_at,endAt:option.end_at,label:option.label,reason:option.reason,source:option.source})),selectedOptionId:meeting.selected_option_id,activeResponder:meeting.active_responder,version:meeting.version,createdAt:meeting.created_at,updatedAt:meeting.updated_at,deliveries:(deliveries??[]).map((delivery)=>({channel:delivery.channel,status:"simulated",label:`Simulated ${delivery.channel} delivery`})),actorId,actorRole:actor.role,bookingPath};}
export async function listMeetings(request:Request){const actor=await meetingActor(request);if(!isSupabaseConfigured())return listPreviewMeetings(actor.id);const admin=createAdminSupabaseClient();const {data}=await admin.from("meeting_participants").select("meeting_id").eq("user_id",actor.id);return Promise.all((data??[]).map((entry)=>realMeetingCard(entry.meeting_id,actor.id)));}
export async function createMeeting(command:string,request:Request){const actor=await meetingActor(request);if(!isSupabaseConfigured())return createPreviewMeeting(command,actor);const intent=interpretMeetingCommand(command);if(intent.ambiguity)return{status:"needs_input" as const,question:intent.ambiguity};const admin=createAdminSupabaseClient();const {data:profiles}=await admin.from("profiles").select("id,email,full_name,username,timezone,active_start,active_end,schedule_version").limit(100);const normalized=intent.participant.toLowerCase(),recipient=intent.participantEmail?null:(profiles??[]).find((profile)=>profile.id!==actor.id&&[profile.email,profile.full_name,profile.username].some((value:string)=>value?.toLowerCase()===normalized||value?.toLowerCase().includes(normalized)));
  if(!recipient&&!intent.participantEmail)return{status:"needs_input" as const,question:"I could not find that Kairos connection. Use Chloe or enter a guest email address."};
  if(recipient){const [{data:connection},{data:permission}]=await Promise.all([admin.from("connections").select("id").eq("status","accepted").or(`and(requester_id.eq.${actor.id},addressee_id.eq.${recipient.id}),and(requester_id.eq.${recipient.id},addressee_id.eq.${actor.id})`).maybeSingle(),admin.from("schedule_permissions").select("scope").eq("owner_id",recipient.id).eq("grantee_id",actor.id).eq("scope","free_busy").maybeSingle()]);if(!connection||!permission)return{status:"needs_input" as const,question:"This person has not granted free/busy access for meeting coordination."};}
  const participantCalendar=recipient?(await admin.from("calendar_items").select("*").eq("user_id",recipient.id).neq("status","cancelled")).data?.map((row)=>mapCalendarRow(row))??[]:[];
  const options=findMeetingOptions(actor,{timezone:recipient?.timezone??actor.timezone,activeStart:recipient?.active_start??"09:00",activeEnd:recipient?.active_end??"18:00"},await getCalendarItems(),participantCalendar,intent.rangeStart,intent.rangeEnd,intent.durationMinutes);if(!options.length)return{status:"impossible" as const,error:"No shared opening fits the requested range and active hours."};
  const token=intent.participantEmail?randomBytes(24).toString("base64url"):null,tokenHash=token?createHash("sha256").update(token).digest("hex"):null;const supabase=await createServerSupabaseClient();const {data:id,error}=await supabase.rpc("create_meeting_request",{p_title:intent.title,p_duration:intent.durationMinutes,p_range_start:intent.rangeStart,p_range_end:intent.rangeEnd,p_timezone:actor.timezone,p_recipient_user:recipient?.id??null,p_recipient_email:intent.participantEmail,p_recipient_name:recipient?.full_name??intent.participant,p_send:intent.mode==="send",p_options:options,p_token_hash:tokenHash,p_token_expires:token?new Date(Date.now()+7*24*60*60_000).toISOString():null});if(error)throw new Error("Kairos could not create this meeting request safely.");return{status:"meeting" as const,meeting:await realMeetingCard(id,actor.id,token?`/book/${token}`:null)};
}
export async function actOnMeeting(id:string,action:string,payload:{optionId?:string;counterStart?:string},request:Request){const actor=await meetingActor(request);if(!isSupabaseConfigured())return actOnPreviewMeeting(id,actor.id,action,payload);const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc("respond_to_meeting",{p_meeting_id:id,p_action:action,p_option_id:payload.optionId??null,p_counter_start:payload.counterStart??null});if(error)throw new Error(/changed|conflict/i.test(error.message)?"A participant's schedule changed. Generate fresh options.":"That meeting response is no longer valid.");return realMeetingCard(id,actor.id);}
