import { cache } from "react";
import { redirect } from "next/navigation";
import { demoViewer, getDemoCalendarItems, getDemoScheduleVersion, mapCalendarRow } from "@/lib/demo-data";
import { isSupabaseConfigured } from "@/lib/env";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import type { CalendarItem, Preference, Viewer } from "@/lib/types";
export const getViewer = cache(async (): Promise<Viewer> => { if (!isSupabaseConfigured()) return {...demoViewer,scheduleVersion:getDemoScheduleVersion()}; const supabase = await createServerSupabaseClient(); const {data,error}=await supabase.auth.getUser(); if(error||!data.user) redirect("/auth"); const {data:p}=await supabase.from("profiles").select("full_name,username,timezone,active_start,active_end,avatar_url,schedule_version").eq("id",data.user.id).single(); return {id:data.user.id,email:data.user.email??"",fullName:p?.full_name??"Kairos user",username:p?.username??data.user.id.slice(0,8),timezone:p?.timezone??"Asia/Manila",activeStart:p?.active_start??"07:00",activeEnd:p?.active_end??"22:30",avatarUrl:p?.avatar_url??null,preview:false,scheduleVersion:p?.schedule_version??1}; });
export const getCalendarItems = cache(async (): Promise<CalendarItem[]> => { if(!isSupabaseConfigured()) return getDemoCalendarItems(); const supabase=await createServerSupabaseClient(); const [{data,error},{data:dependencies,error:dependencyError}]=await Promise.all([supabase.from("calendar_items").select("*").order("start_at",{ascending:true,nullsFirst:false}),supabase.from("calendar_item_dependencies").select("item_id,depends_on_id")]); if(error||dependencyError) throw new Error("Unable to load your schedule."); const byItem=new Map<string,string[]>();for(const dependency of dependencies??[]){const list=byItem.get(dependency.item_id)??[];list.push(dependency.depends_on_id);byItem.set(dependency.item_id,list);} return (data??[]).map(row=>mapCalendarRow({...row,dependency_ids:byItem.get(row.id)??[]})); });
export const getPreferences = cache(async (): Promise<Preference[]> => { if(!isSupabaseConfigured()) return []; const supabase=await createServerSupabaseClient(); const {data,error}=await supabase.from("preferences").select("id,category,default_duration_minutes,flexibility,can_shorten,can_split,can_skip"); if(error) throw new Error("Unable to load preferences."); return (data??[]).map(row=>({id:String(row.id),category:String(row.category),defaultDurationMinutes:row.default_duration_minutes,flexibility:row.flexibility,canShorten:row.can_shorten,canSplit:row.can_split,canSkip:row.can_skip})); });
