-- KAIROS COMPLETE SCHEMA — SQL EDITOR QUICK INSTALL
-- Generated from the ordered Phase 0–6 migrations plus hosted Demo mode.
-- Intended for a NEW Supabase project. Run this entire file once in
-- Supabase Dashboard > SQL Editor > New query.
--
-- This creates application tables, functions, RLS policies, Realtime tables,
-- destinations, the private attachment bucket, and the Profile demo seeder.
-- It does NOT store Vercel or API secrets and does not create passwords.

begin;

-- ============================================================
-- 202607180001_phase0_foundation.sql
-- ============================================================
create extension if not exists pgcrypto with schema extensions;
do $$ begin create type public.calendar_item_type as enum ('event','task','deadline','preparation'); exception when duplicate_object then null; end $$;
do $$ begin create type public.flexibility_mode as enum ('fixed','protected','flexible'); exception when duplicate_object then null; end $$;
do $$ begin create type public.calendar_item_status as enum ('scheduled','in_progress','completed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.proposal_status as enum ('draft','approved','rejected','stale'); exception when duplicate_object then null; end $$;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text not null,full_name text not null,username text not null unique,avatar_url text,timezone text not null default 'Asia/Manila',active_start time not null default '07:00',active_end time not null default '22:30',onboarding_completed boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint profiles_username_format check(username~'^[a-z0-9_]{3,32}$'));
create table if not exists public.schedule_proposals(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,proposal_type text not null check(proposal_type in('creation','repair')),status public.proposal_status not null default 'draft',base_schedule_version integer not null default 1,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.calendar_items(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,item_type public.calendar_item_type not null,title text not null check(char_length(title) between 1 and 160),description text,start_at timestamptz,end_at timestamptz,due_at timestamptz,timezone text not null default 'Asia/Manila',priority smallint not null default 3 check(priority between 1 and 5),flexibility public.flexibility_mode not null default 'flexible',earliest_start timestamptz,latest_end timestamptz,normal_duration_minutes integer,minimum_duration_minutes integer,minimum_chunk_minutes integer,can_shorten boolean not null default false,can_split boolean not null default false,can_skip boolean not null default false,location_label text,recurrence_rule text,related_deadline_id uuid references public.calendar_items(id) on delete set null,status public.calendar_item_status not null default 'scheduled',version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint calendar_items_range check(start_at is null or end_at is null or end_at>start_at),constraint calendar_items_shape check((item_type='deadline' and due_at is not null and start_at is null and end_at is null)or(item_type<>'deadline' and start_at is not null and end_at is not null)));
create table if not exists public.preferences(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,category text not null,default_duration_minutes integer,flexibility public.flexibility_mode,can_shorten boolean not null default false,can_split boolean not null default false,can_skip boolean not null default false,source text not null default 'explicit' check(source='explicit'),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,category));
create table if not exists public.audit_events(id bigint generated by default as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,action text not null,entity_type text not null,entity_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),constraint audit_no_private_payload check(not(metadata ?| array['raw_audio','exact_coordinates','service_role_key','access_token'])));
create or replace function public.set_updated_at()returns trigger language plpgsql security invoker set search_path='' as $$ begin new.updated_at=now();return new;end $$;
create or replace function public.handle_new_user()returns trigger language plpgsql security definer set search_path='' as $$ declare u text;begin u:=lower(regexp_replace(coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)),'[^a-zA-Z0-9_]','','g'));if char_length(u)<3 then u:='kairos_user';end if;u:=left(u,23)||'_'||left(replace(new.id::text,'-',''),8);insert into public.profiles(id,email,full_name,username)values(new.id,coalesce(new.email,''),coalesce(nullif(new.raw_user_meta_data->>'full_name',''),split_part(coalesce(new.email,'Kairos user'),'@',1)),u)on conflict(id)do nothing;return new;end $$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
do $$ declare t text;begin foreach t in array array['profiles','calendar_items','preferences','schedule_proposals','audit_events'] loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);end loop;end $$;
create policy profiles_select_own on public.profiles for select to authenticated using(id=(select auth.uid()));create policy profiles_update_own on public.profiles for update to authenticated using(id=(select auth.uid()))with check(id=(select auth.uid()));
create policy items_select_own on public.calendar_items for select to authenticated using(user_id=(select auth.uid()));create policy items_insert_own on public.calendar_items for insert to authenticated with check(user_id=(select auth.uid()));create policy items_update_own on public.calendar_items for update to authenticated using(user_id=(select auth.uid()))with check(user_id=(select auth.uid()));create policy items_delete_own on public.calendar_items for delete to authenticated using(user_id=(select auth.uid()));
create policy prefs_select_own on public.preferences for select to authenticated using(user_id=(select auth.uid()));create policy prefs_insert_own on public.preferences for insert to authenticated with check(user_id=(select auth.uid()));create policy prefs_update_own on public.preferences for update to authenticated using(user_id=(select auth.uid()))with check(user_id=(select auth.uid()));create policy prefs_delete_own on public.preferences for delete to authenticated using(user_id=(select auth.uid()));
create policy proposals_select_own on public.schedule_proposals for select to authenticated using(user_id=(select auth.uid()));create policy proposals_insert_own on public.schedule_proposals for insert to authenticated with check(user_id=(select auth.uid()));create policy proposals_update_own on public.schedule_proposals for update to authenticated using(user_id=(select auth.uid()))with check(user_id=(select auth.uid()));create policy proposals_delete_own on public.schedule_proposals for delete to authenticated using(user_id=(select auth.uid()));
create policy audit_select_own on public.audit_events for select to authenticated using(user_id=(select auth.uid()));create policy audit_insert_own on public.audit_events for insert to authenticated with check(user_id=(select auth.uid()));
revoke all on public.profiles,public.calendar_items,public.preferences,public.schedule_proposals,public.audit_events from anon;grant select,update on public.profiles to authenticated;grant select,insert,update,delete on public.calendar_items,public.preferences,public.schedule_proposals to authenticated;grant select,insert on public.audit_events to authenticated;

-- ============================================================
-- 202607180002_phase1_conversational_planning.sql
-- ============================================================
alter table public.profiles
  add column if not exists schedule_version bigint not null default 1 check (schedule_version > 0);

alter table public.calendar_items
  add column if not exists category text check (category is null or char_length(category) between 1 and 60),
  add column if not exists reminder_minutes integer not null default 10 check (reminder_minutes between 0 and 10080),
  add column if not exists source_proposal_id uuid references public.schedule_proposals(id) on delete set null;

create table if not exists public.ai_usage (
  user_id uuid not null references public.profiles(id) on delete cascade,
  usage_date date not null,
  text_requests integer not null default 0 check (text_requests >= 0),
  audio_seconds integer not null default 0 check (audio_seconds >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

alter table public.ai_usage enable row level security;
alter table public.ai_usage force row level security;
drop policy if exists "ai_usage_select_own" on public.ai_usage;
create policy "ai_usage_select_own" on public.ai_usage
  for select to authenticated using (user_id = (select auth.uid()));
revoke all on public.ai_usage from anon, authenticated;
grant select on public.ai_usage to authenticated;

create or replace function public.reserve_ai_usage(p_kind text, p_units integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  today_manila date := (timezone('Asia/Manila', now()))::date;
  current_text integer;
  current_audio integer;
begin
  if requesting_user is null or p_kind not in ('text', 'audio') or p_units < 1 then
    return false;
  end if;

  insert into public.ai_usage (user_id, usage_date)
  values (requesting_user, today_manila)
  on conflict (user_id, usage_date) do nothing;

  select text_requests, audio_seconds into current_text, current_audio
  from public.ai_usage
  where user_id = requesting_user and usage_date = today_manila
  for update;

  if (p_kind = 'text' and current_text + p_units > 40)
    or (p_kind = 'audio' and current_audio + p_units > 300) then
    return false;
  end if;

  update public.ai_usage
  set text_requests = text_requests + case when p_kind = 'text' then p_units else 0 end,
      audio_seconds = audio_seconds + case when p_kind = 'audio' then p_units else 0 end,
      updated_at = now()
  where user_id = requesting_user and usage_date = today_manila;
  return true;
end;
$$;

revoke all on function public.reserve_ai_usage(text, integer) from public;
grant execute on function public.reserve_ai_usage(text, integer) to authenticated;

create or replace function public.confirm_schedule_proposal(
  p_proposal_id uuid,
  p_items jsonb,
  p_preferences jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  proposal_record public.schedule_proposals%rowtype;
  current_version bigint;
  item jsonb;
  preference jsonb;
  item_type public.calendar_item_type;
  item_start timestamptz;
  item_end timestamptz;
  item_due timestamptz;
  item_latest timestamptz;
  inserted_ids jsonb := '[]'::jsonb;
  inserted_id uuid;
begin
  if requesting_user is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 20 then
    raise exception 'Proposal must contain between 1 and 20 items';
  end if;

  select * into proposal_record
  from public.schedule_proposals
  where id = p_proposal_id and user_id = requesting_user
  for update;
  if not found then raise exception 'Proposal not found' using errcode = '42501'; end if;
  if proposal_record.status <> 'draft' then raise exception 'Proposal is no longer pending'; end if;

  select schedule_version into current_version
  from public.profiles
  where id = requesting_user
  for update;
  if current_version <> proposal_record.base_schedule_version then
    update public.schedule_proposals set status = 'stale' where id = p_proposal_id;
    raise exception 'Schedule changed; regenerate this proposal' using errcode = '40001';
  end if;

  for item in select value from jsonb_array_elements(p_items)
  loop
    item_type := (item ->> 'type')::public.calendar_item_type;
    item_start := nullif(item ->> 'start_at', '')::timestamptz;
    item_end := nullif(item ->> 'end_at', '')::timestamptz;
    item_due := nullif(item ->> 'due_at', '')::timestamptz;
    item_latest := nullif(item ->> 'latest_end', '')::timestamptz;

    if char_length(coalesce(item ->> 'title', '')) not between 1 and 160 then raise exception 'Invalid item title'; end if;
    if item_type = 'deadline' then
      if item_due is null or item_start is not null or item_end is not null then raise exception 'Invalid deadline shape'; end if;
    else
      if item_start is null or item_end is null or item_end <= item_start then raise exception 'Invalid timed item'; end if;
      if item_latest is not null and item_end > item_latest then raise exception 'Item extends past its allowed window'; end if;
      if coalesce((item ->> 'minimum_duration_minutes')::integer, 0) > extract(epoch from (item_end - item_start)) / 60 then
        raise exception 'Item is shorter than its minimum duration';
      end if;
      if exists (
        select 1 from public.calendar_items existing
        where existing.user_id = requesting_user
          and existing.status <> 'cancelled'
          and existing.start_at is not null and existing.end_at is not null
          and existing.start_at < item_end and existing.end_at > item_start
      ) then raise exception 'Item conflicts with the current schedule'; end if;
    end if;

    insert into public.calendar_items (
      user_id, item_type, title, start_at, end_at, due_at, timezone, priority,
      flexibility, earliest_start, latest_end, normal_duration_minutes,
      minimum_duration_minutes, minimum_chunk_minutes, can_shorten, can_split,
      can_skip, category, reminder_minutes, source_proposal_id
    ) values (
      requesting_user, item_type, item ->> 'title', item_start, item_end, item_due,
      coalesce(item ->> 'timezone', 'Asia/Manila'), coalesce((item ->> 'priority')::smallint, 3),
      coalesce((item ->> 'flexibility')::public.flexibility_mode, 'flexible'),
      nullif(item ->> 'earliest_start', '')::timestamptz, item_latest,
      nullif(item ->> 'normal_duration_minutes', '')::integer,
      nullif(item ->> 'minimum_duration_minutes', '')::integer,
      nullif(item ->> 'minimum_chunk_minutes', '')::integer,
      coalesce((item ->> 'can_shorten')::boolean, false),
      coalesce((item ->> 'can_split')::boolean, false),
      coalesce((item ->> 'can_skip')::boolean, false),
      nullif(item ->> 'category', ''), coalesce((item ->> 'reminder_minutes')::integer, 10),
      p_proposal_id
    ) returning id into inserted_id;
    inserted_ids := inserted_ids || to_jsonb(inserted_id);
  end loop;

  if jsonb_typeof(p_preferences) = 'array' then
    for preference in select value from jsonb_array_elements(p_preferences)
    loop
      insert into public.preferences (
        user_id, category, default_duration_minutes, flexibility,
        can_shorten, can_split, can_skip, source
      ) values (
        requesting_user, preference ->> 'category',
        nullif(preference ->> 'default_duration_minutes', '')::integer,
        nullif(preference ->> 'flexibility', '')::public.flexibility_mode,
        coalesce((preference ->> 'can_shorten')::boolean, false),
        coalesce((preference ->> 'can_split')::boolean, false),
        coalesce((preference ->> 'can_skip')::boolean, false), 'explicit'
      ) on conflict (user_id, category) do update set
        default_duration_minutes = excluded.default_duration_minutes,
        flexibility = excluded.flexibility,
        can_shorten = excluded.can_shorten,
        can_split = excluded.can_split,
        can_skip = excluded.can_skip,
        source = 'explicit',
        updated_at = now();
    end loop;
  end if;

  update public.schedule_proposals
  set status = 'approved', payload = jsonb_set(payload, '{items}', p_items, true), updated_at = now()
  where id = p_proposal_id;
  update public.profiles set schedule_version = schedule_version + 1 where id = requesting_user;
  insert into public.audit_events (user_id, action, entity_type, entity_id, metadata)
  values (requesting_user, 'proposal_confirmed', 'schedule_proposal', p_proposal_id, jsonb_build_object('item_count', jsonb_array_length(p_items)));

  return jsonb_build_object('proposal_id', p_proposal_id, 'item_ids', inserted_ids, 'schedule_version', current_version + 1);
end;
$$;

revoke all on function public.confirm_schedule_proposal(uuid, jsonb, jsonb) from public;
grant execute on function public.confirm_schedule_proposal(uuid, jsonb, jsonb) to authenticated;

-- ============================================================
-- 202607180003_phase2_schedule_repair.sql
-- ============================================================
-- Phase 2: atomic, versioned repair approval. Repair payloads are generated by the
-- deterministic server engine; clients can choose an alternative but cannot edit it.

create table if not exists public.calendar_item_dependencies(
  item_id uuid not null references public.calendar_items(id) on delete cascade,
  depends_on_id uuid not null references public.calendar_items(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  primary key(item_id,depends_on_id),
  constraint dependency_not_self check(item_id<>depends_on_id)
);
alter table public.calendar_item_dependencies enable row level security;
alter table public.calendar_item_dependencies force row level security;
create policy dependencies_select_own on public.calendar_item_dependencies for select to authenticated using(user_id=(select auth.uid()));
revoke all on public.calendar_item_dependencies from anon,authenticated;
grant select on public.calendar_item_dependencies to authenticated;

revoke insert, update, delete on public.calendar_items from authenticated;

create or replace function public.confirm_repair_proposal(
  p_proposal_id uuid,
  p_alternative_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  proposal_record public.schedule_proposals%rowtype;
  current_version bigint;
  alternative jsonb;
  operation jsonb;
  part jsonb;
  original public.calendar_items%rowtype;
  first_part jsonb;
  part_index integer;
  item_start timestamptz;
  item_end timestamptz;
begin
  if requesting_user is null then raise exception 'Authentication required' using errcode='42501'; end if;

  select * into proposal_record from public.schedule_proposals
  where id=p_proposal_id and user_id=requesting_user and proposal_type='repair'
  for update;
  if not found then raise exception 'Repair proposal not found' using errcode='42501'; end if;
  if proposal_record.status<>'draft' then raise exception 'Repair proposal is stale'; end if;

  select schedule_version into current_version from public.profiles
  where id=requesting_user for update;
  if current_version<>proposal_record.base_schedule_version then
    update public.schedule_proposals set status='stale',updated_at=now() where id=p_proposal_id;
    raise exception 'Schedule changed; regenerate repair' using errcode='40001';
  end if;

  select value into alternative
  from jsonb_array_elements(proposal_record.payload->'alternatives')
  where value->>'id'=p_alternative_id limit 1;
  if alternative is null then raise exception 'Repair alternative not found'; end if;

  for operation in select value from jsonb_array_elements(alternative->'operations') loop
    select * into original from public.calendar_items
    where id=(operation->>'itemId')::uuid and user_id=requesting_user
    for update;
    if not found then raise exception 'Repair item no longer exists'; end if;
    if original.flexibility='fixed' then raise exception 'Fixed commitments cannot move'; end if;

    if operation->>'kind'='skip' then
      if not original.can_skip then raise exception 'Item is not optional'; end if;
      update public.calendar_items set status='cancelled',version=version+1,updated_at=now() where id=original.id;
      continue;
    end if;

    if jsonb_array_length(operation->'after')<1 then raise exception 'Repair operation has no result'; end if;
    first_part:=operation->'after'->0;
    item_start:=(first_part->>'startAt')::timestamptz;
    item_end:=(first_part->>'endAt')::timestamptz;
    if item_end<=item_start then raise exception 'Invalid repair duration'; end if;
    if original.earliest_start is not null and item_start<original.earliest_start then raise exception 'Repair starts before allowed window'; end if;
    if original.latest_end is not null and item_end>original.latest_end then raise exception 'Repair ends after allowed window'; end if;
    if operation->>'kind'='shorten' and (not original.can_shorten or extract(epoch from(item_end-item_start))/60<coalesce(original.minimum_duration_minutes,0)) then raise exception 'Invalid shortening'; end if;
    if operation->>'kind'='split' and not original.can_split then raise exception 'Item cannot split'; end if;

    update public.calendar_items set start_at=item_start,end_at=item_end,version=version+1,updated_at=now() where id=original.id;

    if operation->>'kind'='split' then
      part_index:=0;
      for part in select value from jsonb_array_elements(operation->'after') loop
        part_index:=part_index+1;
        if part_index=1 then continue; end if;
        item_start:=(part->>'startAt')::timestamptz;
        item_end:=(part->>'endAt')::timestamptz;
        if extract(epoch from(item_end-item_start))/60<coalesce(original.minimum_chunk_minutes,15) then raise exception 'Split fragment is too short'; end if;
        insert into public.calendar_items(
          user_id,item_type,title,description,start_at,end_at,due_at,timezone,priority,
          flexibility,earliest_start,latest_end,normal_duration_minutes,minimum_duration_minutes,
          minimum_chunk_minutes,can_shorten,can_split,can_skip,location_label,recurrence_rule,
          related_deadline_id,category,reminder_minutes,status,source_proposal_id
        ) values(
          requesting_user,original.item_type,original.title||' · Part '||part_index,original.description,
          item_start,item_end,null,original.timezone,original.priority,original.flexibility,
          original.earliest_start,original.latest_end,original.normal_duration_minutes,
          original.minimum_duration_minutes,original.minimum_chunk_minutes,original.can_shorten,
          original.can_split,original.can_skip,original.location_label,null,original.related_deadline_id,
          original.category,original.reminder_minutes,'scheduled',p_proposal_id
        );
      end loop;
    end if;
  end loop;

  if exists(
    select 1 from public.calendar_items a join public.calendar_items b
      on a.user_id=b.user_id and a.id<b.id and a.status='scheduled' and b.status='scheduled'
      and a.start_at is not null and b.start_at is not null
      and a.start_at<b.end_at and a.end_at>b.start_at
    where a.user_id=requesting_user
  ) then raise exception 'Repair creates a calendar conflict'; end if;

  if exists(
    select 1 from public.calendar_items preparation join public.calendar_items deadline
      on deadline.id=preparation.related_deadline_id
    where preparation.user_id=requesting_user and preparation.status='scheduled'
      and preparation.end_at>deadline.due_at
  ) then raise exception 'Repair extends preparation past its deadline'; end if;

  if exists(
    select 1 from public.calendar_item_dependencies dependency
    join public.calendar_items item on item.id=dependency.item_id
    join public.calendar_items prerequisite on prerequisite.id=dependency.depends_on_id
    where dependency.user_id=requesting_user and item.status='scheduled' and prerequisite.status='scheduled'
      and item.start_at<prerequisite.end_at
  ) then raise exception 'Repair violates an item dependency'; end if;

  update public.schedule_proposals set status='approved',updated_at=now() where id=p_proposal_id;
  update public.schedule_proposals set status='stale',updated_at=now()
    where user_id=requesting_user and status='draft' and id<>p_proposal_id;
  update public.profiles set schedule_version=schedule_version+1 where id=requesting_user;
  insert into public.audit_events(user_id,action,entity_type,entity_id,metadata)
  values(requesting_user,'repair_confirmed','schedule_proposal',p_proposal_id,
    jsonb_build_object('alternative_id',p_alternative_id,'operation_count',jsonb_array_length(alternative->'operations')));
  return jsonb_build_object('proposal_id',p_proposal_id,'schedule_version',current_version+1);
end;
$$;

revoke all on function public.confirm_repair_proposal(uuid,text) from public;
grant execute on function public.confirm_repair_proposal(uuid,text) to authenticated;

-- ============================================================
-- 202607180004_phase3_meeting_coordination.sql
-- ============================================================
do $$ begin create type public.meeting_state as enum('draft','options_sent','awaiting_sender_confirmation','confirmed','declined','expired','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.connection_state as enum('pending','accepted','blocked'); exception when duplicate_object then null; end $$;

create table if not exists public.connections(
  id uuid primary key default gen_random_uuid(),requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,status public.connection_state not null default 'pending',created_at timestamptz not null default now(),
  constraint connection_not_self check(requester_id<>addressee_id),unique(requester_id,addressee_id)
);
create table if not exists public.schedule_permissions(
  owner_id uuid not null references public.profiles(id) on delete cascade,grantee_id uuid not null references public.profiles(id) on delete cascade,
  scope text not null default 'free_busy' check(scope in('none','free_busy')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,grantee_id)
);
create table if not exists public.meeting_requests(
  id uuid primary key default gen_random_uuid(),created_by uuid not null references public.profiles(id) on delete cascade,title text not null check(char_length(title) between 1 and 160),
  duration_minutes integer not null check(duration_minutes between 15 and 480),range_start timestamptz not null,range_end timestamptz not null,timezone text not null,
  state public.meeting_state not null default 'draft',selected_option_id uuid,active_responder uuid references public.profiles(id) on delete set null,version integer not null default 1,base_schedule_versions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint meeting_range_valid check(range_end>range_start)
);
create table if not exists public.meeting_participants(
  meeting_id uuid not null references public.meeting_requests(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,email text,name text not null,
  role text not null check(role in('organizer','recipient')),created_at timestamptz not null default now(),
  constraint participant_identity check((user_id is not null)::integer+(email is not null)::integer=1),unique(meeting_id,user_id),unique(meeting_id,email)
);
create table if not exists public.meeting_options(
  id uuid primary key default gen_random_uuid(),meeting_id uuid not null references public.meeting_requests(id) on delete cascade,start_at timestamptz not null,end_at timestamptz not null,
  label text not null,reason text not null,source text not null check(source in('kairos','counter')),created_by uuid references public.profiles(id) on delete set null,version integer not null default 1,created_at timestamptz not null default now(),constraint option_range_valid check(end_at>start_at)
);
alter table public.meeting_requests drop constraint if exists meeting_requests_selected_option_id_fkey;
alter table public.meeting_requests add constraint meeting_requests_selected_option_id_fkey foreign key(selected_option_id) references public.meeting_options(id) on delete set null deferrable initially deferred;
create table if not exists public.meeting_transitions(
  id bigint generated by default as identity primary key,meeting_id uuid not null references public.meeting_requests(id) on delete cascade,from_state public.meeting_state,to_state public.meeting_state not null,
  actor_id uuid references public.profiles(id) on delete set null,version integer not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now()
);
create table if not exists public.external_booking_tokens(
  id uuid primary key default gen_random_uuid(),meeting_id uuid not null unique references public.meeting_requests(id) on delete cascade,token_hash text not null unique,
  expires_at timestamptz not null,revoked_at timestamptz,created_at timestamptz not null default now()
);
create table if not exists public.simulated_deliveries(
  id uuid primary key default gen_random_uuid(),meeting_id uuid not null references public.meeting_requests(id) on delete cascade,channel text not null check(channel in('email','sms')),
  destination_masked text not null,status text not null default 'simulated' check(status='simulated'),created_at timestamptz not null default now()
);

do $$ declare table_name text; begin foreach table_name in array array['connections','schedule_permissions','meeting_requests','meeting_participants','meeting_options','meeting_transitions','external_booking_tokens','simulated_deliveries'] loop execute format('alter table public.%I enable row level security',table_name);execute format('alter table public.%I force row level security',table_name);end loop;end $$;
create or replace function public.can_access_meeting(p_meeting_id uuid)returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.meeting_requests m where m.id=p_meeting_id and (m.created_by=auth.uid() or exists(select 1 from public.meeting_participants p where p.meeting_id=m.id and p.user_id=auth.uid()))) $$;
revoke all on function public.can_access_meeting(uuid) from public;grant execute on function public.can_access_meeting(uuid) to authenticated;
create policy connections_participants_select on public.connections for select to authenticated using(requester_id=(select auth.uid()) or addressee_id=(select auth.uid()));
create policy permissions_owner_or_grantee_select on public.schedule_permissions for select to authenticated using(owner_id=(select auth.uid()) or grantee_id=(select auth.uid()));
create policy meeting_requests_participant_select on public.meeting_requests for select to authenticated using(public.can_access_meeting(id));
create policy meeting_participants_own_select on public.meeting_participants for select to authenticated using(public.can_access_meeting(meeting_id));
create policy meeting_options_participant_select on public.meeting_options for select to authenticated using(public.can_access_meeting(meeting_id));
create policy meeting_transitions_participant_select on public.meeting_transitions for select to authenticated using(public.can_access_meeting(meeting_id));
create policy deliveries_organizer_select on public.simulated_deliveries for select to authenticated using(exists(select 1 from public.meeting_requests m where m.id=meeting_id and m.created_by=(select auth.uid())));
revoke all on public.connections,public.schedule_permissions,public.meeting_requests,public.meeting_participants,public.meeting_options,public.meeting_transitions,public.external_booking_tokens,public.simulated_deliveries from anon,authenticated;
grant select on public.connections,public.schedule_permissions,public.meeting_requests,public.meeting_participants,public.meeting_options,public.meeting_transitions,public.simulated_deliveries to authenticated;

create or replace function public.create_meeting_request(p_title text,p_duration integer,p_range_start timestamptz,p_range_end timestamptz,p_timezone text,p_recipient_user uuid,p_recipient_email text,p_recipient_name text,p_send boolean,p_options jsonb,p_token_hash text default null,p_token_expires timestamptz default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();meeting_id uuid;option jsonb;recipient_name text;recipient_email text;recipient_active uuid;base_versions jsonb;initial_state public.meeting_state:=case when p_send then 'options_sent'::public.meeting_state else 'draft'::public.meeting_state end;
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  if p_duration not between 15 and 480 or p_range_end<=p_range_start or jsonb_array_length(p_options) not between 1 and 5 then raise exception 'Invalid meeting request';end if;
  if p_recipient_user is not null then
    if not exists(select 1 from public.connections where status='accepted' and ((requester_id=actor and addressee_id=p_recipient_user)or(requester_id=p_recipient_user and addressee_id=actor))) then raise exception 'Connection required' using errcode='42501';end if;
    if not exists(select 1 from public.schedule_permissions where owner_id=p_recipient_user and grantee_id=actor and scope='free_busy') then raise exception 'Free busy permission required' using errcode='42501';end if;
    select full_name,email into recipient_name,recipient_email from public.profiles where id=p_recipient_user;
    recipient_active:=case when p_send then p_recipient_user else actor end;
  else
    if p_recipient_email is null or p_token_hash is null or p_token_expires<=now() then raise exception 'External recipient requires an expiring token';end if;
    recipient_name:=p_recipient_name;recipient_email:=p_recipient_email;recipient_active:=case when p_send then null else actor end;
  end if;
  base_versions:=jsonb_build_object(actor::text,(select schedule_version from public.profiles where id=actor));
  if p_recipient_user is not null then base_versions:=base_versions||jsonb_build_object(p_recipient_user::text,(select schedule_version from public.profiles where id=p_recipient_user));end if;
  insert into public.meeting_requests(created_by,title,duration_minutes,range_start,range_end,timezone,state,active_responder,base_schedule_versions)values(actor,p_title,p_duration,p_range_start,p_range_end,p_timezone,initial_state,recipient_active,base_versions)returning id into meeting_id;
  insert into public.meeting_participants(meeting_id,user_id,name,role)select meeting_id,actor,full_name,'organizer' from public.profiles where id=actor;
  insert into public.meeting_participants(meeting_id,user_id,email,name,role)values(meeting_id,p_recipient_user,case when p_recipient_user is null then recipient_email end,recipient_name,'recipient');
  for option in select value from jsonb_array_elements(p_options) loop insert into public.meeting_options(id,meeting_id,start_at,end_at,label,reason,source,created_by)values((option->>'id')::uuid,meeting_id,(option->>'startAt')::timestamptz,(option->>'endAt')::timestamptz,option->>'label',option->>'reason','kairos',actor);end loop;
  if p_recipient_user is null then insert into public.external_booking_tokens(meeting_id,token_hash,expires_at)values(meeting_id,p_token_hash,p_token_expires);if p_send then insert into public.simulated_deliveries(meeting_id,channel,destination_masked)values(meeting_id,'email','***@'||split_part(recipient_email,'@',2));end if;end if;
  insert into public.meeting_transitions(meeting_id,to_state,actor_id,version)values(meeting_id,initial_state,actor,1);return meeting_id;
end $$;
revoke all on function public.create_meeting_request(text,integer,timestamptz,timestamptz,text,uuid,text,text,boolean,jsonb,text,timestamptz) from public;grant execute on function public.create_meeting_request(text,integer,timestamptz,timestamptz,text,uuid,text,text,boolean,jsonb,text,timestamptz) to authenticated;

create or replace function public.respond_to_meeting(p_meeting_id uuid,p_action text,p_option_id uuid default null,p_counter_start timestamptz default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();meeting public.meeting_requests%rowtype;role_name text;old_state public.meeting_state;recipient_id uuid;chosen public.meeting_options%rowtype;counter_id uuid;
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  select * into meeting from public.meeting_requests where id=p_meeting_id for update;if not found then raise exception 'Meeting not found' using errcode='42501';end if;
  select role into role_name from public.meeting_participants where meeting_id=p_meeting_id and user_id=actor;if role_name is null then raise exception 'Not a participant' using errcode='42501';end if;
  if meeting.state in('confirmed','declined','expired','cancelled') then raise exception 'Meeting already closed';end if;old_state:=meeting.state;
  if p_action='send' and role_name='organizer' and meeting.state='draft' then select user_id into recipient_id from public.meeting_participants where meeting_id=p_meeting_id and role='recipient';update public.meeting_requests set state='options_sent',active_responder=recipient_id,version=version+1,updated_at=now() where id=p_meeting_id;
  elsif p_action='accept' and role_name='recipient' and meeting.state='options_sent' then if not exists(select 1 from public.meeting_options where id=p_option_id and meeting_id=p_meeting_id)then raise exception 'Invalid option';end if;update public.meeting_requests set state='awaiting_sender_confirmation',selected_option_id=p_option_id,active_responder=created_by,version=version+1,updated_at=now()where id=p_meeting_id;
  elsif p_action='counter' and role_name='recipient' and meeting.state='options_sent' then if p_counter_start is null or p_counter_start<meeting.range_start or p_counter_start+make_interval(mins=>meeting.duration_minutes)>meeting.range_end then raise exception 'Counter outside range';end if;insert into public.meeting_options(meeting_id,start_at,end_at,label,reason,source,created_by)values(p_meeting_id,p_counter_start,p_counter_start+make_interval(mins=>meeting.duration_minutes),to_char(p_counter_start at time zone meeting.timezone,'Dy, FMHH12:MI AM'),'Recipient counteroffer','counter',actor)returning id into counter_id;update public.meeting_requests set state='awaiting_sender_confirmation',selected_option_id=counter_id,active_responder=created_by,version=version+1,updated_at=now()where id=p_meeting_id;
  elsif p_action='decline' and role_name='recipient' and meeting.state='options_sent' then update public.meeting_requests set state='declined',active_responder=null,version=version+1,updated_at=now()where id=p_meeting_id;
  elsif p_action='cancel' and role_name='organizer' then update public.meeting_requests set state='cancelled',active_responder=null,version=version+1,updated_at=now()where id=p_meeting_id;
  elsif p_action='confirm' and role_name='organizer' and meeting.state='awaiting_sender_confirmation' then
    select * into chosen from public.meeting_options where id=meeting.selected_option_id and meeting_id=p_meeting_id;if not found then raise exception 'Selected option missing';end if;
    if exists(select 1 from public.meeting_participants participant join public.profiles profile on profile.id=participant.user_id where participant.meeting_id=p_meeting_id and profile.schedule_version<>coalesce((meeting.base_schedule_versions->>(participant.user_id::text))::integer,-1))then raise exception 'Participant schedule changed' using errcode='40001';end if;
    if exists(select 1 from public.meeting_participants participant join public.calendar_items item on item.user_id=participant.user_id where participant.meeting_id=p_meeting_id and item.status='scheduled' and item.start_at<chosen.end_at and item.end_at>chosen.start_at)then raise exception 'Participant schedule changed' using errcode='40001';end if;
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,normal_duration_minutes,minimum_duration_minutes,category,source_proposal_id)
      select participant.user_id,'event',meeting.title,'Confirmed through Kairos',chosen.start_at,chosen.end_at,meeting.timezone,4,'fixed',meeting.duration_minutes,meeting.duration_minutes,'Meeting',null from public.meeting_participants participant where participant.meeting_id=p_meeting_id and participant.user_id is not null;
    update public.profiles set schedule_version=schedule_version+1 where id in(select user_id from public.meeting_participants where meeting_id=p_meeting_id and user_id is not null);
    update public.meeting_requests set state='confirmed',active_responder=null,version=version+1,updated_at=now()where id=p_meeting_id;
  else raise exception 'Invalid meeting transition';end if;
  select * into meeting from public.meeting_requests where id=p_meeting_id;insert into public.meeting_transitions(meeting_id,from_state,to_state,actor_id,version,metadata)values(p_meeting_id,old_state,meeting.state,actor,meeting.version,jsonb_build_object('action',p_action));return jsonb_build_object('meeting_id',p_meeting_id,'state',meeting.state,'version',meeting.version);
end $$;
revoke all on function public.respond_to_meeting(uuid,text,uuid,timestamptz) from public;grant execute on function public.respond_to_meeting(uuid,text,uuid,timestamptz) to authenticated;

create or replace function public.respond_to_external_booking(p_token_hash text,p_action text,p_option_id uuid default null,p_counter_start timestamptz default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare token_record public.external_booking_tokens%rowtype;meeting public.meeting_requests%rowtype;counter_id uuid;old_state public.meeting_state;
begin
  select * into token_record from public.external_booking_tokens where token_hash=p_token_hash for update;
  if not found or token_record.revoked_at is not null or token_record.expires_at<=now() then raise exception 'Booking token invalid or expired' using errcode='42501';end if;
  select * into meeting from public.meeting_requests where id=token_record.meeting_id for update;
  if meeting.state<>'options_sent' then raise exception 'Booking no longer awaiting response';end if;old_state:=meeting.state;
  if p_action='accept' then if not exists(select 1 from public.meeting_options where id=p_option_id and meeting_id=meeting.id)then raise exception 'Invalid option';end if;update public.meeting_requests set state='awaiting_sender_confirmation',selected_option_id=p_option_id,active_responder=created_by,version=version+1,updated_at=now()where id=meeting.id;
  elsif p_action='counter' then if p_counter_start is null or p_counter_start<meeting.range_start or p_counter_start+make_interval(mins=>meeting.duration_minutes)>meeting.range_end then raise exception 'Counter outside range';end if;insert into public.meeting_options(meeting_id,start_at,end_at,label,reason,source)values(meeting.id,p_counter_start,p_counter_start+make_interval(mins=>meeting.duration_minutes),to_char(p_counter_start at time zone meeting.timezone,'Dy, FMHH12:MI AM'),'Guest counteroffer','counter')returning id into counter_id;update public.meeting_requests set state='awaiting_sender_confirmation',selected_option_id=counter_id,active_responder=created_by,version=version+1,updated_at=now()where id=meeting.id;
  elsif p_action='decline' then update public.meeting_requests set state='declined',active_responder=null,version=version+1,updated_at=now()where id=meeting.id;
  else raise exception 'Invalid external response';end if;
  select * into meeting from public.meeting_requests where id=token_record.meeting_id;insert into public.meeting_transitions(meeting_id,from_state,to_state,version,metadata)values(meeting.id,old_state,meeting.state,meeting.version,jsonb_build_object('external',true,'action',p_action));return jsonb_build_object('meeting_id',meeting.id,'state',meeting.state,'version',meeting.version);
end $$;
revoke all on function public.respond_to_external_booking(text,text,uuid,timestamptz) from public;grant execute on function public.respond_to_external_booking(text,text,uuid,timestamptz) to service_role;

do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='meeting_requests')then alter publication supabase_realtime add table public.meeting_requests;end if;end $$;

-- ============================================================
-- 202607180005_phase4_inbox_and_files.sql
-- ============================================================
-- Phase 4: private one-to-one conversations, immutable system updates, and
-- server-mediated private attachments. Group conversations are intentionally deferred.

create table if not exists public.direct_conversations(
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references public.profiles(id) on delete cascade,
  pair_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.direct_conversation_members(
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  removed_at timestamptz,
  primary key(conversation_id,user_id)
);
create table if not exists public.conversation_messages(
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  sender_kind text not null check(sender_kind in('user','system')),
  message_type text not null check(message_type in('text','system_reminder','system_lateness','meeting_card','repair_card')),
  body text not null check(char_length(body) between 1 and 4000),
  client_nonce uuid not null,
  private_to uuid references public.profiles(id) on delete cascade,
  related_meeting_id uuid references public.meeting_requests(id) on delete set null,
  related_proposal_id uuid references public.schedule_proposals(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint message_sender_shape check((sender_kind='user' and sender_id is not null and message_type='text')or(sender_kind='system' and sender_id is null and message_type<>'text')),
  unique(conversation_id,client_nonce)
);
create table if not exists public.message_attachments(
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  message_id uuid not null references public.conversation_messages(id) on delete cascade,
  uploaded_by uuid not null references public.profiles(id) on delete cascade,
  storage_path text not null unique,
  display_name text not null check(char_length(display_name) between 1 and 180),
  mime_type text not null check(mime_type in('application/pdf','image/png','image/jpeg','image/webp','text/plain')),
  size_bytes bigint not null check(size_bytes between 1 and 10485760),
  created_at timestamptz not null default now()
);

do $$ declare table_name text;begin foreach table_name in array array['direct_conversations','direct_conversation_members','conversation_messages','message_attachments'] loop execute format('alter table public.%I enable row level security',table_name);execute format('alter table public.%I force row level security',table_name);end loop;end $$;

create or replace function public.can_access_conversation(p_conversation_id uuid)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.direct_conversation_members member where member.conversation_id=p_conversation_id and member.user_id=auth.uid() and member.removed_at is null)
$$;
revoke all on function public.can_access_conversation(uuid) from public;
grant execute on function public.can_access_conversation(uuid) to authenticated;

create policy conversations_active_member_select on public.direct_conversations for select to authenticated using(public.can_access_conversation(id));
create policy members_active_member_select on public.direct_conversation_members for select to authenticated using(public.can_access_conversation(conversation_id));
create policy messages_active_member_select on public.conversation_messages for select to authenticated using(public.can_access_conversation(conversation_id) and(private_to is null or private_to=(select auth.uid())));
create policy attachments_active_member_select on public.message_attachments for select to authenticated using(public.can_access_conversation(conversation_id) and exists(select 1 from public.conversation_messages message where message.id=message_attachments.message_id and(message.private_to is null or message.private_to=(select auth.uid()))));

revoke all on public.direct_conversations,public.direct_conversation_members,public.conversation_messages,public.message_attachments from anon,authenticated;
grant select on public.direct_conversations,public.direct_conversation_members,public.conversation_messages,public.message_attachments to authenticated;

create or replace function public.ensure_direct_conversation(p_other_user uuid)
returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();conversation_id uuid;canonical_pair text;
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  if actor=p_other_user then raise exception 'A direct conversation needs another person';end if;
  if not exists(select 1 from public.connections where status='accepted' and((requester_id=actor and addressee_id=p_other_user)or(requester_id=p_other_user and addressee_id=actor)))then raise exception 'An accepted connection is required' using errcode='42501';end if;
  canonical_pair:=case when actor::text<p_other_user::text then actor::text||':'||p_other_user::text else p_other_user::text||':'||actor::text end;
  insert into public.direct_conversations(created_by,pair_key)values(actor,canonical_pair)on conflict(pair_key)do update set updated_at=now() returning id into conversation_id;
  insert into public.direct_conversation_members(conversation_id,user_id)values(conversation_id,actor),(conversation_id,p_other_user)on conflict(conversation_id,user_id)do nothing;
  return conversation_id;
end $$;
revoke all on function public.ensure_direct_conversation(uuid) from public;
grant execute on function public.ensure_direct_conversation(uuid) to authenticated;

create or replace function public.send_conversation_message(p_conversation_id uuid,p_body text,p_client_nonce uuid,p_related_meeting uuid default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();message_id uuid;
begin
  if actor is null or not public.can_access_conversation(p_conversation_id)then raise exception 'Conversation access denied' using errcode='42501';end if;
  if char_length(trim(p_body))not between 1 and 4000 then raise exception 'Message body is invalid';end if;
  if p_related_meeting is not null and not public.can_access_meeting(p_related_meeting)then raise exception 'Meeting access denied' using errcode='42501';end if;
  insert into public.conversation_messages(conversation_id,sender_id,sender_kind,message_type,body,client_nonce,related_meeting_id)values(p_conversation_id,actor,'user','text',trim(p_body),p_client_nonce,p_related_meeting)on conflict(conversation_id,client_nonce)do nothing returning id into message_id;
  if message_id is null then select id into message_id from public.conversation_messages where conversation_id=p_conversation_id and client_nonce=p_client_nonce;end if;
  update public.direct_conversations set updated_at=now()where id=p_conversation_id;
  return message_id;
end $$;
revoke all on function public.send_conversation_message(uuid,text,uuid,uuid) from public;
grant execute on function public.send_conversation_message(uuid,text,uuid,uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('kairos-attachments','kairos-attachments',false,10485760,array['application/pdf','image/png','image/jpeg','image/webp','text/plain'])
on conflict(id)do update set public=false,file_size_limit=10485760,allowed_mime_types=excluded.allowed_mime_types;

-- Files are uploaded and signed only by authenticated server routes after an active
-- membership check. Browser roles receive no direct storage object privileges.
drop policy if exists kairos_attachments_direct_select on storage.objects;
drop policy if exists kairos_attachments_direct_insert on storage.objects;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='conversation_messages')then alter publication supabase_realtime add table public.conversation_messages;end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='message_attachments')then alter publication supabase_realtime add table public.message_attachments;end if;
end $$;

-- ============================================================
-- 202607180006_phase5_profiles_permissions_activity.sql
-- ============================================================
-- Phase 5: profile controls, connection lifecycle, category permissions,
-- explicit preferences, and private server-generated activity.

alter table public.profiles
  add column if not exists location_enabled boolean not null default false,
  add column if not exists automation_reminders boolean not null default true,
  add column if not exists automation_lateness boolean not null default true,
  add column if not exists activity_aggregate_sharing boolean not null default false;

alter table public.schedule_permissions drop constraint if exists schedule_permissions_scope_check;
alter table public.schedule_permissions add column if not exists categories text[] not null default '{}'::text[];
alter table public.schedule_permissions add constraint schedule_permissions_scope_check check(scope in('none','free_busy','categories')and(scope='categories' or cardinality(categories)=0)and(scope<>'categories' or cardinality(categories)between 1 and 20));

create table if not exists public.private_activity_events(
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  activity_type text not null check(activity_type in('task_completion','deadline','meeting','preparation','schedule_adherence')),
  entity_id uuid,
  title text not null check(char_length(title)between 1 and 160),
  score smallint not null default 1 check(score between 1 and 4),
  source_key text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint private_activity_no_sensitive_metadata check(not(metadata ?| array['location','coordinates','attachment','event_title','raw_content'])),
  unique(user_id,source_key)
);
alter table public.private_activity_events enable row level security;
alter table public.private_activity_events force row level security;
create policy private_activity_select_own on public.private_activity_events for select to authenticated using(user_id=(select auth.uid()));
revoke all on public.private_activity_events from anon,authenticated;
grant select on public.private_activity_events to authenticated;
revoke insert on public.audit_events from authenticated;

create or replace function public.manage_connection(p_connection_id uuid,p_action text)
returns text language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();connection_record public.connections%rowtype;
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  select * into connection_record from public.connections where id=p_connection_id and(actor=requester_id or actor=addressee_id)for update;
  if not found then raise exception 'Connection not found' using errcode='42501';end if;
  if p_action='accept' then if actor<>connection_record.addressee_id or connection_record.status<>'pending' then raise exception 'Only the recipient can accept a pending connection';end if;update public.connections set status='accepted' where id=connection_record.id;
  elsif p_action='block' then update public.connections set status='blocked' where id=connection_record.id;delete from public.schedule_permissions where(owner_id=connection_record.requester_id and grantee_id=connection_record.addressee_id)or(owner_id=connection_record.addressee_id and grantee_id=connection_record.requester_id);update public.direct_conversation_members set removed_at=now()where conversation_id in(select conversation_id from public.direct_conversation_members where user_id in(connection_record.requester_id,connection_record.addressee_id)group by conversation_id having count(distinct user_id)=2);
  elsif p_action='remove' then delete from public.schedule_permissions where(owner_id=connection_record.requester_id and grantee_id=connection_record.addressee_id)or(owner_id=connection_record.addressee_id and grantee_id=connection_record.requester_id);update public.direct_conversation_members set removed_at=now()where conversation_id in(select conversation_id from public.direct_conversation_members where user_id in(connection_record.requester_id,connection_record.addressee_id)group by conversation_id having count(distinct user_id)=2);delete from public.connections where id=connection_record.id;return 'removed';
  else raise exception 'Invalid connection action';end if;return p_action;
end $$;
revoke all on function public.manage_connection(uuid,text) from public;
grant execute on function public.manage_connection(uuid,text) to authenticated;

create or replace function public.update_schedule_permission(p_grantee uuid,p_scope text,p_categories text[] default '{}'::text[])
returns void language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();clean_categories text[];
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  if not exists(select 1 from public.connections where status='accepted' and((requester_id=actor and addressee_id=p_grantee)or(requester_id=p_grantee and addressee_id=actor)))then raise exception 'Accepted connection required' using errcode='42501';end if;
  if p_scope not in('none','free_busy','categories')then raise exception 'Invalid permission scope';end if;
  select coalesce(array_agg(distinct left(trim(value),60))filter(where trim(value)<>''),'{}'::text[])into clean_categories from unnest(coalesce(p_categories,'{}'::text[]))value;
  if p_scope='categories' and cardinality(clean_categories)not between 1 and 20 then raise exception 'Choose 1 to 20 categories';end if;
  insert into public.schedule_permissions(owner_id,grantee_id,scope,categories)values(actor,p_grantee,p_scope,case when p_scope='categories'then clean_categories else '{}'::text[]end)on conflict(owner_id,grantee_id)do update set scope=excluded.scope,categories=excluded.categories,updated_at=now();
end $$;
revoke all on function public.update_schedule_permission(uuid,text,text[]) from public;
grant execute on function public.update_schedule_permission(uuid,text,text[]) to authenticated;

create or replace function public.complete_calendar_item(p_item_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();item public.calendar_items%rowtype;activity_kind text;on_time boolean;
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  select * into item from public.calendar_items where id=p_item_id and user_id=actor for update;
  if not found then raise exception 'Calendar item not found' using errcode='42501';end if;
  if item.item_type not in('task','preparation')or item.status<>'scheduled'then raise exception 'This item cannot be completed';end if;
  activity_kind:=case when item.item_type='preparation'then 'preparation'else 'task_completion'end;on_time:=item.end_at is null or now()<=item.end_at+interval '15 minutes';
  update public.calendar_items set status='completed',version=version+1,updated_at=now()where id=item.id;
  update public.profiles set schedule_version=schedule_version+1 where id=actor;
  insert into public.private_activity_events(user_id,activity_type,entity_id,title,score,source_key)values(actor,activity_kind,item.id,item.title,case when on_time then 3 else 2 end,'complete:'||item.id::text)on conflict(user_id,source_key)do nothing;
  if on_time then insert into public.private_activity_events(user_id,activity_type,entity_id,title,score,source_key)values(actor,'schedule_adherence',item.id,'Protected time followed',2,'adherence:'||item.id::text)on conflict(user_id,source_key)do nothing;end if;
  return jsonb_build_object('item_id',item.id,'status','completed','schedule_version',(select schedule_version from public.profiles where id=actor));
end $$;
revoke all on function public.complete_calendar_item(uuid) from public;
grant execute on function public.complete_calendar_item(uuid) to authenticated;

create or replace function public.get_shared_activity_aggregate(p_user uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();result jsonb;
begin
  if actor is null or not exists(select 1 from public.profiles where id=p_user and activity_aggregate_sharing=true)or not exists(select 1 from public.connections where status='accepted' and((requester_id=actor and addressee_id=p_user)or(requester_id=p_user and addressee_id=actor)))then return null;end if;
  select jsonb_build_object('active_days',count(distinct created_at::date),'total_actions',count(*),'current_streak',0)into result from public.private_activity_events where user_id=p_user and created_at>=now()-interval '30 days';return result;
end $$;
revoke all on function public.get_shared_activity_aggregate(uuid) from public;
grant execute on function public.get_shared_activity_aggregate(uuid) to authenticated;

-- ============================================================
-- 202607180007_sql_editor_demo_mode.sql
-- ============================================================
-- Quick-hosting support: an authenticated user may seed or remove their own
-- database-backed demo schedule from Profile. This keeps the Vercel demo on
-- Supabase instead of relying on process memory.

alter table public.profiles add column if not exists demo_mode boolean not null default false;
alter table public.calendar_items add column if not exists demo_seeded boolean not null default false;
alter table public.preferences add column if not exists demo_seeded boolean not null default false;

create or replace function public.set_demo_mode(p_enabled boolean)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  actor uuid:=auth.uid();
  actor_email text;
  counterpart_email text;
  counterpart uuid;
  connection_id uuid;
  conversation_id uuid;
  canonical_pair text;
  base_day timestamptz;
  class_id uuid;
  gym_id uuid;
  deadline_id uuid;
  seeded_items integer:=0;
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  select email into actor_email from public.profiles where id=actor for update;
  if actor_email is null then raise exception 'Profile not found' using errcode='42501';end if;

  if not p_enabled then
    delete from public.calendar_items where user_id=actor and demo_seeded=true;
    get diagnostics seeded_items=row_count;
    delete from public.preferences where user_id=actor and demo_seeded=true;
    delete from public.private_activity_events where user_id=actor and source_key like 'demo:%';
    update public.profiles set demo_mode=false,schedule_version=schedule_version+1,updated_at=now()where id=actor;
    return jsonb_build_object('enabled',false,'removed_items',seeded_items);
  end if;

  update public.profiles set demo_mode=true,updated_at=now()where id=actor;
  if not exists(select 1 from public.calendar_items where user_id=actor and demo_seeded=true)then
    base_day:=(date_trunc('day',now()at time zone 'Asia/Manila')at time zone 'Asia/Manila');
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,normal_duration_minutes,minimum_duration_minutes,location_label,category,recurrence_rule,demo_seeded)
      values(actor,'event','Systems Design Class','Kairos hosted demo data',base_day+interval '10 hours',base_day+interval '11 hours 30 minutes','Asia/Manila',4,'fixed',90,90,'Engineering Building','Class','FREQ=WEEKLY;BYDAY=MO,WE',true)returning id into class_id;
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,earliest_start,latest_end,normal_duration_minutes,minimum_duration_minutes,location_label,category,demo_seeded)
      values(actor,'task','Gym Session','Kairos hosted demo data',base_day+interval '12 hours 15 minutes',base_day+interval '13 hours 15 minutes','Asia/Manila',3,'flexible',base_day+interval '11 hours 30 minutes',base_day+interval '18 hours',60,60,'Campus Gym','Fitness',true)returning id into gym_id;
    insert into public.calendar_items(user_id,item_type,title,description,due_at,timezone,priority,flexibility,category,demo_seeded)
      values(actor,'deadline','Research Paper Due','Kairos hosted demo data',base_day+interval '3 days 17 hours','Asia/Manila',5,'fixed','Deadline',true)returning id into deadline_id;
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,earliest_start,latest_end,normal_duration_minutes,minimum_duration_minutes,minimum_chunk_minutes,can_split,location_label,related_deadline_id,category,demo_seeded)
      values(actor,'preparation','Paper Research','Kairos hosted demo data',base_day+interval '14 hours',base_day+interval '15 hours 30 minutes','Asia/Manila',4,'flexible',base_day+interval '13 hours 30 minutes',base_day+interval '1 day 19 hours',90,90,30,true,'Library',deadline_id,'Preparation',true);
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,normal_duration_minutes,minimum_duration_minutes,location_label,category,demo_seeded)
      values(actor,'event','Team Project Sync','Kairos hosted demo data',base_day+interval '1 day 15 hours',base_day+interval '1 day 16 hours','Asia/Manila',3,'protected',60,60,'Online','Meeting',true);
    insert into public.calendar_item_dependencies(item_id,depends_on_id,user_id)values(gym_id,class_id,actor)on conflict do nothing;
    get diagnostics seeded_items=row_count;
    seeded_items:=5;
    update public.profiles set schedule_version=schedule_version+1 where id=actor;
  end if;

  insert into public.preferences(user_id,category,default_duration_minutes,flexibility,can_shorten,can_split,can_skip,source,demo_seeded)
    values(actor,'Fitness',60,'flexible',false,false,false,'explicit',true),(actor,'Preparation',90,'protected',false,true,false,'explicit',true)
    on conflict(user_id,category)do nothing;
  insert into public.private_activity_events(user_id,activity_type,title,score,source_key,created_at)
    select actor,(array['task_completion','deadline','meeting','preparation','schedule_adherence'])[1+(entry%5)],(array['Task completed','Deadline protected','Meeting coordinated','Preparation finished','Protected time followed'])[1+(entry%5)],1+(entry%4),'demo:'||entry::text,now()-(entry*2+1)*interval '1 day'
    from generate_series(0,33)entry on conflict(user_id,source_key)do nothing;

  -- If both standard rehearsal accounts already registered through Supabase Auth,
  -- enabling Demo mode on either account connects them automatically.
  counterpart_email:=case when lower(actor_email)='demo@kairos.app'then'chloe@kairos.app'when lower(actor_email)='chloe@kairos.app'then'demo@kairos.app'else null end;
  if counterpart_email is not null then
    select id into counterpart from public.profiles where lower(email)=counterpart_email limit 1;
    if counterpart is not null then
      select id into connection_id from public.connections where(requester_id=actor and addressee_id=counterpart)or(requester_id=counterpart and addressee_id=actor)limit 1;
      if connection_id is null then insert into public.connections(requester_id,addressee_id,status)values(actor,counterpart,'accepted')returning id into connection_id;else update public.connections set status='accepted'where id=connection_id;end if;
      insert into public.schedule_permissions(owner_id,grantee_id,scope,categories)values(actor,counterpart,'free_busy','{}'::text[]),(counterpart,actor,'free_busy','{}'::text[])on conflict(owner_id,grantee_id)do nothing;
      canonical_pair:=case when actor::text<counterpart::text then actor::text||':'||counterpart::text else counterpart::text||':'||actor::text end;
      insert into public.direct_conversations(created_by,pair_key)values(actor,canonical_pair)on conflict(pair_key)do update set updated_at=now()returning id into conversation_id;
      insert into public.direct_conversation_members(conversation_id,user_id)values(conversation_id,actor),(conversation_id,counterpart)on conflict(conversation_id,user_id)do update set removed_at=null;
    end if;
  end if;
  return jsonb_build_object('enabled',true,'seeded_items',seeded_items,'demo_connection_ready',counterpart is not null);
end $$;
revoke all on function public.set_demo_mode(boolean)from public;
grant execute on function public.set_demo_mode(boolean)to authenticated;

-- ============================================================
-- 202607180008_phase6_live_eta.sql
-- ============================================================
-- Phase 6: stored destinations and user-controlled travel buffers.
-- Origin GPS coordinates remain request-scoped and are never written to the database.

alter table public.profiles add column if not exists travel_buffer_minutes integer not null default 15 check(travel_buffer_minutes between 0 and 120);
alter table public.calendar_items add column if not exists destination_latitude double precision check(destination_latitude between -90 and 90);
alter table public.calendar_items add column if not exists destination_longitude double precision check(destination_longitude between -180 and 180);
alter table public.calendar_items add column if not exists destination_place_id text;
alter table public.calendar_items add column if not exists destination_resolved_at timestamptz;

create or replace function public.confirm_schedule_proposal(
  p_proposal_id uuid,
  p_items jsonb,
  p_preferences jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  proposal_record public.schedule_proposals%rowtype;
  current_version bigint;
  item jsonb;
  preference jsonb;
  item_type public.calendar_item_type;
  item_start timestamptz;
  item_end timestamptz;
  item_due timestamptz;
  item_latest timestamptz;
  inserted_ids jsonb := '[]'::jsonb;
  inserted_id uuid;
begin
  if requesting_user is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 20 then
    raise exception 'Proposal must contain between 1 and 20 items';
  end if;

  select * into proposal_record
  from public.schedule_proposals
  where id = p_proposal_id and user_id = requesting_user
  for update;
  if not found then raise exception 'Proposal not found' using errcode = '42501'; end if;
  if proposal_record.status <> 'draft' then raise exception 'Proposal is no longer pending'; end if;

  select schedule_version into current_version
  from public.profiles
  where id = requesting_user
  for update;
  if current_version <> proposal_record.base_schedule_version then
    update public.schedule_proposals set status = 'stale' where id = p_proposal_id;
    raise exception 'Schedule changed; regenerate this proposal' using errcode = '40001';
  end if;

  for item in select value from jsonb_array_elements(p_items)
  loop
    item_type := (item ->> 'type')::public.calendar_item_type;
    item_start := nullif(item ->> 'start_at', '')::timestamptz;
    item_end := nullif(item ->> 'end_at', '')::timestamptz;
    item_due := nullif(item ->> 'due_at', '')::timestamptz;
    item_latest := nullif(item ->> 'latest_end', '')::timestamptz;

    if char_length(coalesce(item ->> 'title', '')) not between 1 and 160 then raise exception 'Invalid item title'; end if;
    if item_type = 'deadline' then
      if item_due is null or item_start is not null or item_end is not null then raise exception 'Invalid deadline shape'; end if;
    else
      if item_start is null or item_end is null or item_end <= item_start then raise exception 'Invalid timed item'; end if;
      if item_latest is not null and item_end > item_latest then raise exception 'Item extends past its allowed window'; end if;
      if coalesce((item ->> 'minimum_duration_minutes')::integer, 0) > extract(epoch from (item_end - item_start)) / 60 then
        raise exception 'Item is shorter than its minimum duration';
      end if;
      if exists (
        select 1 from public.calendar_items existing
        where existing.user_id = requesting_user
          and existing.status <> 'cancelled'
          and existing.start_at is not null and existing.end_at is not null
          and existing.start_at < item_end and existing.end_at > item_start
      ) then raise exception 'Item conflicts with the current schedule'; end if;
    end if;

    insert into public.calendar_items (
      user_id, item_type, title, start_at, end_at, due_at, timezone, priority,
      flexibility, earliest_start, latest_end, normal_duration_minutes,
      minimum_duration_minutes, minimum_chunk_minutes, can_shorten, can_split,
      can_skip, category, location_label, reminder_minutes, source_proposal_id
    ) values (
      requesting_user, item_type, item ->> 'title', item_start, item_end, item_due,
      coalesce(item ->> 'timezone', 'Asia/Manila'), coalesce((item ->> 'priority')::smallint, 3),
      coalesce((item ->> 'flexibility')::public.flexibility_mode, 'flexible'),
      nullif(item ->> 'earliest_start', '')::timestamptz, item_latest,
      nullif(item ->> 'normal_duration_minutes', '')::integer,
      nullif(item ->> 'minimum_duration_minutes', '')::integer,
      nullif(item ->> 'minimum_chunk_minutes', '')::integer,
      coalesce((item ->> 'can_shorten')::boolean, false),
      coalesce((item ->> 'can_split')::boolean, false),
      coalesce((item ->> 'can_skip')::boolean, false),
      nullif(item ->> 'category', ''), nullif(item ->> 'location_label', ''), coalesce((item ->> 'reminder_minutes')::integer, 10),
      p_proposal_id
    ) returning id into inserted_id;
    inserted_ids := inserted_ids || to_jsonb(inserted_id);
  end loop;

  if jsonb_typeof(p_preferences) = 'array' then
    for preference in select value from jsonb_array_elements(p_preferences)
    loop
      insert into public.preferences (
        user_id, category, default_duration_minutes, flexibility,
        can_shorten, can_split, can_skip, source
      ) values (
        requesting_user, preference ->> 'category',
        nullif(preference ->> 'default_duration_minutes', '')::integer,
        nullif(preference ->> 'flexibility', '')::public.flexibility_mode,
        coalesce((preference ->> 'can_shorten')::boolean, false),
        coalesce((preference ->> 'can_split')::boolean, false),
        coalesce((preference ->> 'can_skip')::boolean, false), 'explicit'
      ) on conflict (user_id, category) do update set
        default_duration_minutes = excluded.default_duration_minutes,
        flexibility = excluded.flexibility,
        can_shorten = excluded.can_shorten,
        can_split = excluded.can_split,
        can_skip = excluded.can_skip,
        source = 'explicit',
        updated_at = now();
    end loop;
  end if;

  update public.schedule_proposals
  set status = 'approved', payload = jsonb_set(payload, '{items}', p_items, true), updated_at = now()
  where id = p_proposal_id;
  update public.profiles set schedule_version = schedule_version + 1 where id = requesting_user;
  insert into public.audit_events (user_id, action, entity_type, entity_id, metadata)
  values (requesting_user, 'proposal_confirmed', 'schedule_proposal', p_proposal_id, jsonb_build_object('item_count', jsonb_array_length(p_items)));

  return jsonb_build_object('proposal_id', p_proposal_id, 'item_ids', inserted_ids, 'schedule_version', current_version + 1);
end;
$$;

revoke all on function public.confirm_schedule_proposal(uuid, jsonb, jsonb) from public;
grant execute on function public.confirm_schedule_proposal(uuid, jsonb, jsonb) to authenticated;

create or replace function public.set_demo_mode(p_enabled boolean)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  actor uuid:=auth.uid();
  actor_email text;
  counterpart_email text;
  counterpart uuid;
  connection_id uuid;
  conversation_id uuid;
  canonical_pair text;
  base_day timestamptz;
  class_id uuid;
  gym_id uuid;
  deadline_id uuid;
  seeded_items integer:=0;
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  select email into actor_email from public.profiles where id=actor for update;
  if actor_email is null then raise exception 'Profile not found' using errcode='42501';end if;

  if not p_enabled then
    delete from public.calendar_items where user_id=actor and demo_seeded=true;
    get diagnostics seeded_items=row_count;
    delete from public.preferences where user_id=actor and demo_seeded=true;
    delete from public.private_activity_events where user_id=actor and source_key like 'demo:%';
    update public.profiles set demo_mode=false,schedule_version=schedule_version+1,updated_at=now()where id=actor;
    return jsonb_build_object('enabled',false,'removed_items',seeded_items);
  end if;

  update public.profiles set demo_mode=true,location_enabled=true,updated_at=now()where id=actor;
  if not exists(select 1 from public.calendar_items where user_id=actor and demo_seeded=true)then
    base_day:=(date_trunc('day',now()at time zone 'Asia/Manila')at time zone 'Asia/Manila');
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,normal_duration_minutes,minimum_duration_minutes,location_label,category,recurrence_rule,demo_seeded)
      values(actor,'event','Systems Design Class','Kairos hosted demo data',base_day+interval '10 hours',base_day+interval '11 hours 30 minutes','Asia/Manila',4,'fixed',90,90,'Engineering Building','Class','FREQ=WEEKLY;BYDAY=MO,WE',true)returning id into class_id;
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,earliest_start,latest_end,normal_duration_minutes,minimum_duration_minutes,location_label,category,demo_seeded)
      values(actor,'task','Gym Session','Kairos hosted demo data',base_day+interval '12 hours 15 minutes',base_day+interval '13 hours 15 minutes','Asia/Manila',3,'flexible',base_day+interval '11 hours 30 minutes',base_day+interval '18 hours',60,60,'Campus Gym','Fitness',true)returning id into gym_id;
    insert into public.calendar_items(user_id,item_type,title,description,due_at,timezone,priority,flexibility,category,demo_seeded)
      values(actor,'deadline','Research Paper Due','Kairos hosted demo data',base_day+interval '3 days 17 hours','Asia/Manila',5,'fixed','Deadline',true)returning id into deadline_id;
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,earliest_start,latest_end,normal_duration_minutes,minimum_duration_minutes,minimum_chunk_minutes,can_split,location_label,related_deadline_id,category,demo_seeded)
      values(actor,'preparation','Paper Research','Kairos hosted demo data',base_day+interval '14 hours',base_day+interval '15 hours 30 minutes','Asia/Manila',4,'flexible',base_day+interval '13 hours 30 minutes',base_day+interval '1 day 19 hours',90,90,30,true,'Library',deadline_id,'Preparation',true);
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,normal_duration_minutes,minimum_duration_minutes,location_label,category,demo_seeded)
      values(actor,'event','Team Project Sync','Kairos hosted demo data',base_day+interval '1 day 15 hours',base_day+interval '1 day 16 hours','Asia/Manila',3,'protected',60,60,'Online','Meeting',true);
    insert into public.calendar_item_dependencies(item_id,depends_on_id,user_id)values(gym_id,class_id,actor)on conflict do nothing;
    get diagnostics seeded_items=row_count;
    seeded_items:=5;
    update public.profiles set schedule_version=schedule_version+1 where id=actor;
  end if;

  insert into public.preferences(user_id,category,default_duration_minutes,flexibility,can_shorten,can_split,can_skip,source,demo_seeded)
    values(actor,'Fitness',60,'flexible',false,false,false,'explicit',true),(actor,'Preparation',90,'protected',false,true,false,'explicit',true)
    on conflict(user_id,category)do nothing;
  insert into public.private_activity_events(user_id,activity_type,title,score,source_key,created_at)
    select actor,(array['task_completion','deadline','meeting','preparation','schedule_adherence'])[1+(entry%5)],(array['Task completed','Deadline protected','Meeting coordinated','Preparation finished','Protected time followed'])[1+(entry%5)],1+(entry%4),'demo:'||entry::text,now()-(entry*2+1)*interval '1 day'
    from generate_series(0,33)entry on conflict(user_id,source_key)do nothing;

  -- If both standard rehearsal accounts already registered through Supabase Auth,
  -- enabling Demo mode on either account connects them automatically.
  counterpart_email:=case when lower(actor_email)='demo@kairos.app'then'chloe@kairos.app'when lower(actor_email)='chloe@kairos.app'then'demo@kairos.app'else null end;
  if counterpart_email is not null then
    select id into counterpart from public.profiles where lower(email)=counterpart_email limit 1;
    if counterpart is not null then
      select id into connection_id from public.connections where(requester_id=actor and addressee_id=counterpart)or(requester_id=counterpart and addressee_id=actor)limit 1;
      if connection_id is null then insert into public.connections(requester_id,addressee_id,status)values(actor,counterpart,'accepted')returning id into connection_id;else update public.connections set status='accepted'where id=connection_id;end if;
      insert into public.schedule_permissions(owner_id,grantee_id,scope,categories)values(actor,counterpart,'free_busy','{}'::text[]),(counterpart,actor,'free_busy','{}'::text[])on conflict(owner_id,grantee_id)do nothing;
      canonical_pair:=case when actor::text<counterpart::text then actor::text||':'||counterpart::text else counterpart::text||':'||actor::text end;
      insert into public.direct_conversations(created_by,pair_key)values(actor,canonical_pair)on conflict(pair_key)do update set updated_at=now()returning id into conversation_id;
      insert into public.direct_conversation_members(conversation_id,user_id)values(conversation_id,actor),(conversation_id,counterpart)on conflict(conversation_id,user_id)do update set removed_at=null;
    end if;
  end if;
  return jsonb_build_object('enabled',true,'seeded_items',seeded_items,'demo_connection_ready',counterpart is not null);
end $$;
revoke all on function public.set_demo_mode(boolean)from public;
grant execute on function public.set_demo_mode(boolean)to authenticated;

commit;

-- Successful installation returns ready=true.
select jsonb_build_object(
  'ready',to_regclass('public.profiles')is not null and to_regclass('public.private_activity_events')is not null,
  'latest_feature','phase6_live_eta',
  'attachment_bucket',exists(select 1 from storage.buckets where id='kairos-attachments'),
  'destination_columns',exists(select 1 from information_schema.columns where table_schema='public' and table_name='calendar_items' and column_name='destination_latitude')
)as kairos_installation;
