import { beforeEach,describe,expect,it } from "vitest";
import { addPreviewAttachment, getPreviewAttachment, listPreviewConversation, MAYA_CONVERSATION_ID, PREVIEW_CONVERSATION_ID, recordPreviewSystemMessage, removePreviewConversationMember, resetPreviewConversations, sendPreviewMessage } from "@/lib/conversations/preview-store";
import { DEMO_USER_ID } from "@/lib/demo-data";
import { CHLOE_ID } from "@/lib/meetings/preview-store";
import { validAttachmentBytes } from "@/lib/conversations/files";

beforeEach(()=>resetPreviewConversations());
describe("Phase 4 direct conversations",()=>{
  it("delivers one-to-one messages to both active participants",()=>{sendPreviewMessage(DEMO_USER_ID,PREVIEW_CONVERSATION_ID,"Can we keep a notes buffer?","71111111-1111-4111-8111-111111111111");expect(listPreviewConversation(DEMO_USER_ID)?.messages.at(-1)?.isMine).toBe(true);const chloe=listPreviewConversation(CHLOE_ID)?.messages.at(-1);expect(chloe?.body).toContain("notes buffer");expect(chloe?.isMine).toBe(false);});
  it("deduplicates retried sends by client nonce",()=>{const nonce="71111111-1111-4111-8111-111111111112";const first=sendPreviewMessage(DEMO_USER_ID,PREVIEW_CONVERSATION_ID,"One copy",nonce),second=sendPreviewMessage(DEMO_USER_ID,PREVIEW_CONVERSATION_ID,"One copy",nonce);expect(second).toBe(first);expect(listPreviewConversation(DEMO_USER_ID)?.messages.filter((message)=>message.body==="One copy")).toHaveLength(1);});
  it("keeps each accepted friend's chat separate",()=>{const maya="33333333-3333-4333-8333-333333333333";sendPreviewMessage(DEMO_USER_ID,MAYA_CONVERSATION_ID,"Hi Maya","71111111-1111-4111-8111-111111111119");expect(listPreviewConversation(DEMO_USER_ID,maya)?.messages.at(-1)?.body).toBe("Hi Maya");expect(listPreviewConversation(DEMO_USER_ID,CHLOE_ID)?.messages.some((message)=>message.body==="Hi Maya")).toBe(false);});
  it("keeps private reminders and repair cards away from the other participant",()=>{recordPreviewSystemMessage("repair_card","Private repair approved.","71111111-1111-4111-8111-111111111113",{privateTo:DEMO_USER_ID});expect(listPreviewConversation(DEMO_USER_ID)?.messages.some((message)=>message.body.includes("Private repair"))).toBe(true);expect(listPreviewConversation(CHLOE_ID)?.messages.some((message)=>message.body.includes("Private repair"))).toBe(false);});
  it("identifies automated messages as immutable system senders",()=>{const reminder=listPreviewConversation(DEMO_USER_ID)?.messages.find((message)=>message.type==="system_reminder");expect(reminder).toMatchObject({senderId:null,senderName:"Kairos",senderKind:"system",private:true,isMine:false});});
  it("inherits conversation permission for attachments and revokes it immediately",()=>{const id=addPreviewAttachment(DEMO_USER_ID,PREVIEW_CONVERSATION_ID,{name:"agenda.txt",mimeType:"text/plain",bytes:new TextEncoder().encode("private agenda")},"Agenda attached","71111111-1111-4111-8111-111111111114",null);expect(getPreviewAttachment(CHLOE_ID,id)?.name).toBe("agenda.txt");removePreviewConversationMember(CHLOE_ID);expect(listPreviewConversation(CHLOE_ID)).toBeNull();expect(getPreviewAttachment(CHLOE_ID,id)).toBeNull();expect(getPreviewAttachment("33333333-3333-4333-8333-333333333333",id)).toBeNull();});
  it("rejects spoofed or unsupported file contents",()=>{expect(validAttachmentBytes("application/pdf",new TextEncoder().encode("not a PDF"))).toBe(false);expect(validAttachmentBytes("text/plain",new TextEncoder().encode("safe notes"))).toBe(true);expect(validAttachmentBytes("application/javascript",new TextEncoder().encode("alert(1)"))).toBe(false);});
});
