import "server-only";
import {getCalendarItems}from"@/lib/data";
import {getDemoCalendarItems,getDemoScheduleVersion,replaceDemoCalendarItems}from"@/lib/demo-data";
import {isSupabaseConfigured}from"@/lib/env";
import {getProfileSettings}from"@/lib/profile/server";
import {getServerEnv}from"@/lib/server-env";
import {createServerSupabaseClient}from"@/lib/supabase/server";
import type{PlaceResult,JourneyStatus}from"@/lib/journey/types";
import{haversineMeters}from"@/lib/journey/math";
const seeds=[
 {placeId:"demo-engineering",name:"Engineering Building",address:"University campus, Manila",latitude:14.5999,longitude:120.9891},
 {placeId:"demo-gym",name:"Campus Gym",address:"University athletics center, Manila",latitude:14.6011,longitude:120.9875},
 {placeId:"demo-library",name:"Main Library",address:"University campus, Manila",latitude:14.5987,longitude:120.9858},
 {placeId:"demo-online",name:"Online meeting",address:"No travel required",latitude:14.5995,longitude:120.9842},
];
export async function searchPlaces(query:string):Promise<PlaceResult[]>{const q=query.trim().slice(0,180);if(q.length<2)return[];const key=getServerEnv().GOOGLE_MAPS_API_KEY;if(key){try{const response=await fetch("https://places.googleapis.com/v1/places:searchText",{method:"POST",headers:{"Content-Type":"application/json","X-Goog-Api-Key":key,"X-Goog-FieldMask":"places.id,places.displayName,places.formattedAddress,places.location"},body:JSON.stringify({textQuery:q,pageSize:5,languageCode:"en"}),cache:"no-store"});if(response.ok){const data=await response.json()as{places?:Array<{id:string;displayName?:{text?:string};formattedAddress?:string;location?:{latitude?:number;longitude?:number}}>};return(data.places??[]).flatMap((p)=>Number.isFinite(p.location?.latitude)&&Number.isFinite(p.location?.longitude)?[{placeId:p.id,name:p.displayName?.text??p.formattedAddress??q,address:p.formattedAddress??q,latitude:p.location!.latitude!,longitude:p.location!.longitude!,source:"google"as const}]:[]);}}catch{/* visible fallback below */}}
const words=q.toLowerCase().split(/\s+/);const matches=seeds.filter((p)=>words.some((word)=>p.name.toLowerCase().includes(word)||p.address.toLowerCase().includes(word)));return(matches.length?matches:seeds.slice(0,3)).map((p)=>({...p,source:"seeded_demo"}));}
export async function saveDestination(itemId:string,place:PlaceResult){const items=await getCalendarItems(),item=items.find((entry)=>entry.id===itemId);if(!item)throw new Error("Calendar item not found.");const resolvedAt=new Date().toISOString();if(!isSupabaseConfigured()){const next=getDemoCalendarItems(),target=next.find((entry)=>entry.id===itemId);if(!target)throw new Error("Calendar item not found.");Object.assign(target,{locationLabel:place.address||place.name,destinationLatitude:place.latitude,destinationLongitude:place.longitude,destinationPlaceId:place.placeId,destinationResolvedAt:resolvedAt,version:target.version+1});if(!replaceDemoCalendarItems(next,getDemoScheduleVersion()))throw new Error("Your schedule changed. Try again.");return target;}
const supabase=await createServerSupabaseClient(),{data,error}=await supabase.from("calendar_items").update({location_label:place.address||place.name,destination_latitude:place.latitude,destination_longitude:place.longitude,destination_place_id:place.placeId,destination_resolved_at:resolvedAt}).eq("id",itemId).select("id").single();if(error||!data)throw new Error("Destination could not be saved.");return data;}
function seconds(value:string|undefined){return Math.max(0,Math.ceil(Number(value?.replace("s",""))||0));}
export async function computeJourney(itemId:string,origin:{latitude:number;longitude:number}|null,demo=false):Promise<JourneyStatus>{const[items,settings]=await Promise.all([getCalendarItems(),getProfileSettings()]);if(!settings.locationEnabled&&!demo)throw new Error("Enable Location access in Profile before starting Journey Mode.");const item=items.find((entry)=>entry.id===itemId);if(!item||!item.startAt)throw new Error("Journey Mode needs a scheduled calendar item.");if(item.destinationLatitude==null||item.destinationLongitude==null)throw new Error("Choose a destination first.");const destination={latitude:item.destinationLatitude,longitude:item.destinationLongitude},fallbackOrigin=origin??{latitude:14.5995,longitude:120.9842};let durationSeconds=0,distanceMeters=0,source:"google"|"seeded_demo"="seeded_demo";const key=getServerEnv().GOOGLE_MAPS_API_KEY;
if(key&&origin&&!demo){try{const response=await fetch("https://routes.googleapis.com/directions/v2:computeRoutes",{method:"POST",headers:{"Content-Type":"application/json","X-Goog-Api-Key":key,"X-Goog-FieldMask":"routes.duration,routes.distanceMeters,routes.staticDuration"},body:JSON.stringify({origin:{location:{latLng:{latitude:origin.latitude,longitude:origin.longitude}}},destination:{location:{latLng:destination}},travelMode:"DRIVE",routingPreference:"TRAFFIC_AWARE"}),cache:"no-store"});if(response.ok){const data=await response.json()as{routes?:Array<{duration?:string;distanceMeters?:number}>};const route=data.routes?.[0];if(route){durationSeconds=seconds(route.duration);distanceMeters=route.distanceMeters??0;source="google";}}}catch{/* labeled fallback below */}}
if(!durationSeconds){distanceMeters=Math.round(haversineMeters(fallbackOrigin,destination));durationSeconds=Math.max(6*60,Math.round(distanceMeters/350)*60+8*60);source="seeded_demo";}
const now=Date.now(),durationMinutes=Math.max(1,Math.ceil(durationSeconds/60)),predicted=now+durationSeconds*1000,start=new Date(item.startAt).getTime(),delayMinutes=Math.max(0,Math.ceil((predicted-start)/60000)),leaveAt=start-(durationMinutes+settings.travelBufferMinutes)*60000;return{itemId:item.id,destinationLabel:item.locationLabel??item.title,durationMinutes,distanceMeters,leaveAt:new Date(leaveAt).toISOString(),predictedArrival:new Date(predicted).toISOString(),delayMinutes,freshAt:new Date(now).toISOString(),source,accuracyWarning:source==="google"?"Traffic estimates can change; keep Journey Mode open for updates.":"Seeded demo estimate — not live GPS or traffic."};}
