import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { getCalendarItems, getViewer } from "@/lib/data";
import { DEMO_USER_ID } from "@/lib/demo-data";
import { isSupabaseConfigured } from "@/lib/env";
import { addPreviewAttachment, getPreviewAttachment, listPreviewConversation, recordPreviewSystemMessage, sendPreviewMessage } from "@/lib/conversations/preview-store";
import type { ConversationContact, ConversationMessage, ConversationView, MessageType } from "@/lib/conversations/types";
import type { MeetingCard } from "@/lib/meetings/types";
// Threads load the most recent page; older history stays in the database.
const MESSAGE_PAGE_SIZE = 200;
import { CHLOE_ID, previewActor } from "@/lib/meetings/preview-store";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { ALLOWED_ATTACHMENT_TYPES, MAX_ATTACHMENT_BYTES, validAttachmentBytes } from "@/lib/conversations/files";
import { getProfileSettings,recordPrivateActivity } from "@/lib/profile/server";
import { listPreviewConnections } from "@/lib/profile/preview-store";
import { AppError } from "@/lib/http";

export const ATTACHMENT_BUCKET="kairos-attachments";
export async function conversationActor(request:Request){return isSupabaseConfigured()?getViewer():previewActor(request.headers.get("x-demo-user"));}
function uuidKey(value:string){const hex=createHash("sha256").update(value).digest("hex").slice(0,32).split("");hex[12]="4";hex[16]=((parseInt(hex[16],16)&3)|8).toString(16);return`${hex.slice(0,8).join("")}-${hex.slice(8,12).join("")}-${hex.slice(12,16).join("")}-${hex.slice(16,20).join("")}-${hex.slice(20).join("")}`;}
async function activeMembership(conversationId:string,actorId:string){const admin=createAdminSupabaseClient();const{data}=await admin.from("direct_conversation_members").select("conversation_id").eq("conversation_id",conversationId).eq("user_id",actorId).is("removed_at",null).maybeSingle();return Boolean(data);}
async function findConversationForUsers(first:string,second:string){const admin=createAdminSupabaseClient();const{data:firstRows}=await admin.from("direct_conversation_members").select("conversation_id").eq("user_id",first).is("removed_at",null);const ids=(firstRows??[]).map((row)=>row.conversation_id);if(!ids.length)return null;const{data}=await admin.from("direct_conversation_members").select("conversation_id").eq("user_id",second).is("removed_at",null).in("conversation_id",ids).limit(1).maybeSingle();return data?.conversation_id??null;}
async function ensureConversation(otherUserId:string){const supabase=await createServerSupabaseClient();const result=await supabase.rpc("ensure_direct_conversation",{p_other_user:otherUserId});if(result.error)throw new AppError("You can only message accepted friends.");return result.data as string;}
export async function getConversationContacts(request:Request):Promise<ConversationContact[]>{const actor=await conversationActor(request);if(!isSupabaseConfigured()){if(actor.id===CHLOE_ID)return[{id:DEMO_USER_ID,name:"Justin",email:"justin@kairos.app",permissionScope:"free_busy",incomingPermissionScope:"free_busy"}];return listPreviewConnections().filter((connection)=>connection.status==="accepted").map((connection)=>({id:connection.userId,name:connection.name,email:connection.email,permissionScope:connection.permission.scope,incomingPermissionScope:connection.permission.scope}));}const admin=createAdminSupabaseClient(),{data:connections,error}=await admin.from("connections").select("requester_id,addressee_id").eq("status","accepted").or(`requester_id.eq.${actor.id},addressee_id.eq.${actor.id}`);if(error)throw new AppError("Friends could not be loaded.");const ids=(connections??[]).map((connection)=>connection.requester_id===actor.id?connection.addressee_id:connection.requester_id);if(!ids.length)return[];const[{data:profiles,error:profileError},{data:outgoing},{data:incoming}]=await Promise.all([admin.from("profiles").select("id,full_name,email").in("id",ids).order("full_name"),admin.from("schedule_permissions").select("grantee_id,scope").eq("owner_id",actor.id).in("grantee_id",ids),admin.from("schedule_permissions").select("owner_id,scope").eq("grantee_id",actor.id).in("owner_id",ids)]);if(profileError)throw new AppError("Friends could not be loaded.");const outgoingScopes=new Map((outgoing??[]).map((permission)=>[permission.grantee_id,permission.scope as ConversationContact["permissionScope"]])),incomingScopes=new Map((incoming??[]).map((permission)=>[permission.owner_id,permission.scope as ConversationContact["incomingPermissionScope"]]));return(profiles??[]).map((profile)=>({id:profile.id,name:profile.full_name,email:profile.email,permissionScope:outgoingScopes.get(profile.id)??"none",incomingPermissionScope:incomingScopes.get(profile.id)??"none"}));}
export async function getConversation(request:Request,otherUserId:string):Promise<ConversationView|null>{const actor=await conversationActor(request);if(!isSupabaseConfigured())return listPreviewConversation(actor.id,otherUserId);const id=await findConversationForUsers(actor.id,otherUserId)??await ensureConversation(otherUserId);if(!await activeMembership(id,actor.id))return null;const admin=createAdminSupabaseClient();const[{data:members},{data:messages},{data:attachments}]=await Promise.all([admin.from("direct_conversation_members").select("user_id,profiles!direct_conversation_members_user_id_fkey(full_name,email)").eq("conversation_id",id).is("removed_at",null),admin.from("conversation_messages").select("id,conversation_id,sender_id,sender_kind,message_type,body,private_to,related_meeting_id,created_at").eq("conversation_id",id).or(`private_to.is.null,private_to.eq.${actor.id}`).order("created_at",{ascending:false}).limit(MESSAGE_PAGE_SIZE),admin.from("message_attachments").select("id,message_id,display_name,mime_type,size_bytes").eq("conversation_id",id)]);const other=(members??[]).find((member)=>member.user_id!==actor.id),profile=other?.profiles as unknown as {full_name:string;email:string}|null;const names=new Map((members??[]).map((member)=>[member.user_id,(member.profiles as unknown as {full_name:string}|null)?.full_name??"User"]));const byMessage=new Map<string,Array<{id:string;message_id:string;display_name:string;mime_type:string;size_bytes:number}>>();for(const attachment of attachments??[]){const list=byMessage.get(attachment.message_id)??[];list.push(attachment);byMessage.set(attachment.message_id,list);}// The newest page is fetched descending, then restored to reading order.
const cards=[...(messages??[])].reverse().map((message):ConversationMessage=>({id:message.id,conversationId:message.conversation_id,senderId:message.sender_id,senderName:message.sender_kind==="system"?"Update":names.get(message.sender_id)??"User",senderKind:message.sender_kind,type:message.message_type,body:message.body,isMine:message.sender_id===actor.id,private:Boolean(message.private_to),relatedMeetingId:message.related_meeting_id,createdAt:message.created_at,attachments:(byMessage.get(message.id)??[]).map((entry)=>({id:entry.id,name:entry.display_name,mimeType:entry.mime_type,sizeBytes:entry.size_bytes,downloadPath:`/api/attachments/${entry.id}/download`,previewable:entry.mime_type.startsWith("image/")||entry.mime_type==="application/pdf"||entry.mime_type==="text/plain"}))}));return{id,otherUser:{id:other?.user_id??otherUserId,name:profile?.full_name??"Friend",email:profile?.email??""},messages:cards};}
export async function sendConversationMessage(request:Request,conversationId:string,body:string,clientNonce:string,relatedMeetingId:string|null){const actor=await conversationActor(request);if(!isSupabaseConfigured())return sendPreviewMessage(actor.id,conversationId,body,clientNonce,relatedMeetingId);const supabase=await createServerSupabaseClient();const{data,error}=await supabase.rpc("send_conversation_message",{p_conversation_id:conversationId,p_body:body,p_client_nonce:clientNonce,p_related_meeting:relatedMeetingId});if(error)throw new AppError("This message could not be sent safely.");return data as string;}
function safeName(name:string){return name.normalize("NFKC").replace(/[^a-zA-Z0-9._ -]/g,"_").slice(0,180)||"attachment";}
export async function uploadConversationAttachment(request:Request,conversationId:string,file:File,body:string,clientNonce:string,relatedMeetingId:string|null){const actor=await conversationActor(request);if(!ALLOWED_ATTACHMENT_TYPES.has(file.type))throw new AppError("Use PDF, PNG, JPEG, WebP, or plain text files.");if(file.size<1||file.size>MAX_ATTACHMENT_BYTES)throw new AppError("Attachments must be between 1 byte and 10 MB.");const name=safeName(file.name),bytes=new Uint8Array(await file.arrayBuffer());if(!validAttachmentBytes(file.type,bytes))throw new AppError("The file contents do not match an allowed file type.");if(!isSupabaseConfigured())return addPreviewAttachment(actor.id,conversationId,{name,mimeType:file.type,bytes},body,clientNonce,relatedMeetingId);if(!await activeMembership(conversationId,actor.id))throw new AppError("Conversation access denied.");const messageId=await sendConversationMessage(request,conversationId,body||`Shared ${name}`,clientNonce,relatedMeetingId),attachmentId=randomUUID(),path=`${conversationId}/${attachmentId}-${name}`,admin=createAdminSupabaseClient();
// The message insert is idempotent per nonce, so a retried upload must not attach a second copy.
const prior=await admin.from("message_attachments").select("id").eq("message_id",messageId).maybeSingle();if(prior.data)return prior.data.id;const uploaded=await admin.storage.from(ATTACHMENT_BUCKET).upload(path,bytes,{contentType:file.type,upsert:false});if(uploaded.error)throw new AppError("The attachment could not be stored.");const{error}=await admin.from("message_attachments").insert({id:attachmentId,conversation_id:conversationId,message_id:messageId,uploaded_by:actor.id,storage_path:path,display_name:name,mime_type:file.type,size_bytes:file.size});if(error){await admin.storage.from(ATTACHMENT_BUCKET).remove([path]);throw new AppError("The attachment could not be linked safely.");}return attachmentId;}
export async function downloadAttachment(request:Request,id:string){const actor=!isSupabaseConfigured()?previewActor(new URL(request.url).searchParams.get("demoUser")):await conversationActor(request);if(!isSupabaseConfigured()){const value=getPreviewAttachment(actor.id,id);if(!value)return null;return{kind:"bytes" as const,bytes:value.bytes,mimeType:value.mimeType,name:value.name};}const admin=createAdminSupabaseClient();const{data}=await admin.from("message_attachments").select("conversation_id,storage_path,display_name,mime_type,message_id,conversation_messages!inner(private_to)").eq("id",id).maybeSingle();const privateTo=(data?.conversation_messages as unknown as {private_to:string|null}|null)?.private_to;if(!data||privateTo&&privateTo!==actor.id||!await activeMembership(data.conversation_id,actor.id))return null;const{data:signed,error}=await admin.storage.from(ATTACHMENT_BUCKET).createSignedUrl(data.storage_path,60,{download:data.display_name});if(error||!signed)return null;return{kind:"redirect" as const,url:signed.signedUrl};}
async function insertRealSystemMessage(conversationId:string,type:Exclude<MessageType,"text">,body:string,key:string,options:{privateTo?:string|null;relatedMeetingId?:string|null;relatedProposalId?:string|null}={}){const admin=createAdminSupabaseClient();await admin.from("conversation_messages").upsert({conversation_id:conversationId,sender_id:null,sender_kind:"system",message_type:type,body,client_nonce:uuidKey(key),private_to:options.privateTo??null,related_meeting_id:options.relatedMeetingId??null,related_proposal_id:options.relatedProposalId??null},{onConflict:"conversation_id,client_nonce",ignoreDuplicates:true});}
export async function recordMeetingActivity(meeting:MeetingCard,action:string){const users=meeting.participants.flatMap((participant)=>participant.userId?[participant.userId]:[]);if(users.length!==2)return;const body=action==="created"?`${meeting.participants.find((p)=>p.role==="organizer")?.name??"The organizer"} sent meeting options for ${meeting.title}.`:action==="confirm"?`${meeting.title} was confirmed. Matching planner items were created.`:`${meeting.title} was updated: ${action}.`,key=`meeting:${meeting.id}:${meeting.version}:${action}`;if(action==="confirm")await Promise.all(users.map((userId)=>recordPrivateActivity(userId,"meeting",meeting.title,`meeting:${meeting.id}:confirmed`,3,isSupabaseConfigured()?meeting.id:null)));if(!isSupabaseConfigured()){recordPreviewSystemMessage("meeting_card",body,uuidKey(key),{relatedMeetingId:meeting.id});return;}const conversationId=await findConversationForUsers(users[0],users[1]);if(conversationId)await insertRealSystemMessage(conversationId,"meeting_card",body,key,{relatedMeetingId:meeting.id});}
export async function recordPrivateScheduleActivity(userId:string,body:string,key:string,proposalId:string|null=null){if(!isSupabaseConfigured()){recordPreviewSystemMessage("repair_card",body,uuidKey(key),{privateTo:userId});return;}const admin=createAdminSupabaseClient();const{data}=await admin.from("direct_conversation_members").select("conversation_id").eq("user_id",userId).is("removed_at",null).limit(1).maybeSingle();if(data)await insertRealSystemMessage(data.conversation_id,"repair_card",body,key,{privateTo:userId,relatedProposalId:proposalId});}
export async function ensureAutomatedConversationUpdates(request:Request,conversation:ConversationView){const actor=await conversationActor(request);if(!isSupabaseConfigured())return;const settings=await getProfileSettings();if(!settings.automationReminders&&!settings.automationLateness)return;const now=Date.now(),items=await getCalendarItems();for(const item of items){if(item.status!=="scheduled"||!item.startAt||!item.endAt)continue;const start=new Date(item.startAt).getTime(),end=new Date(item.endAt).getTime();if(settings.automationReminders&&start>=now&&start-now<=30*60_000)await insertRealSystemMessage(conversation.id,"system_reminder",`${item.title} starts in ${Math.max(1,Math.ceil((start-now)/60_000))} minutes.`,`reminder:${actor.id}:${item.id}:${item.startAt}`,{privateTo:actor.id});else if(settings.automationLateness&&end<now&&now-end<=2*60*60_000)await insertRealSystemMessage(conversation.id,"system_lateness",`${item.title} may be running late.`,`lateness:${actor.id}:${item.id}:${item.endAt}`,{privateTo:actor.id});}}

export async function sendApprovedLatenessStatus(request:Request,itemTitle:string,predictedArrival:string,delayMinutes:number){const contacts=await getConversationContacts(request),recipient=contacts.find((contact)=>contact.id===CHLOE_ID)??contacts[0];if(!recipient)throw new AppError("Add a friend before sharing an ETA.");const conversation=await getConversation(request,recipient.id);if(!conversation)throw new AppError("This chat is unavailable.");const time=new Intl.DateTimeFormat("en",{timeZone:"Asia/Manila",hour:"numeric",minute:"2-digit"}).format(new Date(predictedArrival));const body=`Running about ${delayMinutes} minute${delayMinutes===1?"":"s"} late for ${itemTitle}. My estimated arrival is ${time}.`;await sendConversationMessage(request,conversation.id,body,randomUUID(),null);return{conversationId:conversation.id,body};}
