import { expect,test } from "@playwright/test";

test.beforeEach(async({page})=>{await page.request.post("/api/demo/reset");});
test("private activity heatmap sits below schedule repair",async({page})=>{await page.goto("/");await page.waitForLoadState("networkidle");const repair=page.getByRole("region",{name:"Schedule repair"}),heatmap=page.getByRole("region",{name:"Your protected-time rhythm"});await expect(heatmap).toBeVisible();const repairBox=await repair.boundingBox(),heatmapBox=await heatmap.boundingBox();expect(heatmapBox!.y).toBeGreaterThan(repairBox!.y+repairBox!.height-2);await expect(page.getByText("Only you",{exact:true})).toBeVisible();});
test("Justin and Chloe exchange a direct message after selecting the chat",async({page})=>{await page.goto("/inbox");await page.waitForLoadState("networkidle");await expect(page.getByRole("heading",{name:"Select a friend"})).toBeVisible();await expect(page.getByLabel("Write a message")).toHaveCount(0);await page.getByRole("button",{name:"Open chat with Chloe"}).click();await page.getByLabel("Write a message").fill("Please keep the 15-minute notes buffer.");await page.getByRole("button",{name:"Send message"}).click();await expect(page.getByText("Please keep the 15-minute notes buffer.")).toBeVisible();await page.getByRole("button",{name:"chloe",exact:true}).click();await page.getByRole("button",{name:"Open chat with Justin"}).click();await expect(page.getByText("Please keep the 15-minute notes buffer.")).toBeVisible();});
test("message retries do not create duplicates",async({page})=>{const nonce="81111111-1111-4111-8111-111111111111",conversation="44444444-4444-4444-8444-444444444444",body={body:"Exactly once",clientNonce:nonce,relatedMeetingId:null};await page.request.post(`/api/conversations/${conversation}/messages`,{headers:{"x-demo-user":"justin"},data:body});await page.request.post(`/api/conversations/${conversation}/messages`,{headers:{"x-demo-user":"justin"},data:body});await page.goto("/inbox");await page.waitForLoadState("networkidle");await page.getByRole("button",{name:"Open chat with Chloe"}).click();await expect(page.getByText("Exactly once")).toHaveCount(1);});
test("authorized participants can preview a restricted attachment",async({page})=>{await page.goto("/inbox");await page.waitForLoadState("networkidle");await page.getByRole("button",{name:"Open chat with Chloe"}).click();await page.locator('input[type="file"]').setInputFiles({name:"agenda.txt",mimeType:"text/plain",buffer:Buffer.from("private agenda")});await page.getByLabel("Write a message").fill("Agenda for our meeting");await page.getByRole("button",{name:"Send message"}).click();let link=page.getByRole("link",{name:/agenda\.txt/});await expect(link).toBeVisible();const justinPath=await link.getAttribute("href");expect(justinPath).toMatch(/\/api\/attachments\/.+\/download\?demoUser=justin/);expect(await(await page.request.get(justinPath!)).text()).toBe("private agenda");await page.getByRole("button",{name:"chloe",exact:true}).click();await page.getByRole("button",{name:"Open chat with Justin"}).click();link=page.getByRole("link",{name:/agenda\.txt/});await expect(link).toHaveAttribute("href",/demoUser=chloe/);const chloePath=await link.getAttribute("href");expect(await(await page.request.get(chloePath!)).text()).toBe("private agenda");});
test("meeting cards can be discussed without leaving Inbox",async({page})=>{await page.goto("/inbox");await page.waitForLoadState("networkidle");await page.getByRole("button",{name:"Coordinate meeting"}).click();await page.getByRole("button",{name:"Discuss this request"}).click();await expect(page.getByText("Discussing:")).toBeVisible();await expect(page.getByText("Strategy Alignment",{exact:true}).first()).toBeVisible();});
test("private automated reminders do not appear for Chloe",async({page})=>{await page.goto("/inbox");await page.waitForLoadState("networkidle");await page.getByRole("button",{name:"Open chat with Chloe"}).click();await expect(page.getByText(/Paper Research starts in 30 minutes/)).toBeVisible();await page.getByRole("button",{name:"chloe",exact:true}).click();await page.getByRole("button",{name:"Open chat with Justin"}).click();await expect(page.getByText(/Paper Research starts in 30 minutes/)).toHaveCount(0);});
test("users can be found and added from Inbox",async({page})=>{await page.goto("/inbox");await page.waitForLoadState("networkidle");await page.getByRole("search").getByPlaceholder("Name, username, or email").fill("noah");await page.getByRole("button",{name:"Search",exact:true}).click();const result=page.getByRole("article").filter({hasText:"Noah Santos"});await expect(result).toContainText("@noah");await result.getByRole("button",{name:"Add friend"}).click();await expect(page.getByText("Friend request sent to Noah Santos.")).toBeVisible();await expect(result).toContainText("Request sent");});
test("friends can see and control both directions of meeting access",async({page})=>{await page.goto("/inbox");await page.waitForLoadState("networkidle");await expect(page.getByText("Chloe allows you",{exact:true})).toBeVisible();const access=page.getByRole("button",{name:"Stop sharing free/busy with Chloe"});await expect(access).toBeVisible();await access.click();const allow=page.getByRole("button",{name:"Share free/busy with Chloe"});await expect(allow).toBeVisible();await allow.click();await expect(page.getByRole("button",{name:"Stop sharing free/busy with Chloe"})).toBeVisible();});
