import { expect, test } from "@playwright/test";

test("find-times language creates a private unsent draft",async({page})=>{await page.request.post("/api/demo/reset");await page.goto("/inbox");await page.waitForLoadState("networkidle");const command=page.getByLabel("Meeting command");await command.fill("Find 60 minutes with Chloe next week");await page.getByRole("button",{name:"Coordinate meeting"}).click();await expect(page.getByText("Private draft",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Send these options"})).toBeVisible();await expect(page.getByText(/Nothing was sent/)).toBeVisible();});

test("Justin and Chloe complete the final-confirmation flow",async({page},info)=>{test.skip(!info.project.name.includes("desktop"),"single shared-state transaction flow");await page.request.post("/api/demo/reset");await page.goto("/inbox");await page.waitForLoadState("networkidle");await page.getByRole("button",{name:"Coordinate meeting"}).click();await expect(page.getByText("Awaiting recipient",{exact:true})).toBeVisible();await page.getByRole("button",{name:"chloe",exact:true}).click();await expect(page.getByRole("button",{name:"Accept selected time"})).toBeVisible();await page.getByRole("button",{name:"Accept selected time"}).click();await expect(page.getByText("Awaiting sender",{exact:true})).toBeVisible();await page.getByRole("button",{name:"justin",exact:true}).click();await expect(page.getByRole("button",{name:"Final confirmation"})).toBeVisible();await page.getByRole("button",{name:"Final confirmation"}).click();await expect(page.getByText("Confirmed",{exact:true})).toBeVisible();await expect(page.getByText("Matching calendar events created.")).toBeVisible();});

test("meeting cards remain usable on iPhone",async({page},info)=>{test.skip(!info.project.name.includes("iphone"),"iPhone layout check");await page.request.post("/api/demo/reset");await page.goto("/inbox");await page.waitForLoadState("networkidle");await page.getByRole("button",{name:"Coordinate meeting"}).click();await expect(page.getByRole("heading",{name:"Strategy Alignment"})).toBeVisible();await expect(page.getByRole("button",{name:"chloe",exact:true})).toBeVisible();});

test("guest booking link works without an account",async({page},info)=>{test.skip(!info.project.name.includes("desktop"),"single external-token flow");await page.request.post("/api/demo/reset");await page.goto("/inbox");await page.waitForLoadState("networkidle");await page.getByLabel("Meeting command").fill("Schedule a 30 minute review with guest@example.com tomorrow");await page.getByRole("button",{name:"Coordinate meeting"}).click();const link=page.getByRole("link",{name:"Open no-account booking page"});await expect(link).toBeVisible();const path=await link.getAttribute("href");expect(path).toMatch(/^\/book\//);await page.goto(path!);await expect(page.getByRole("heading",{name:"Respond without an account"})).toBeVisible();await page.getByRole("button",{name:"Accept selected time"}).click();await expect(page.getByText(/organizer must give final confirmation/)).toBeVisible();});
