"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { AlertCircle, Bot, Download, FileText, LoaderCircle, LockKeyhole, MessageCircle, Paperclip, Send, Wifi } from "lucide-react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
import type { ConversationView } from "@/lib/conversations/types";

function clock(value:string){return new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(value));}
function size(value:number){return value<1024?`${value} B`:value<1024*1024?`${Math.ceil(value/1024)} KB`:`${(value/1024/1024).toFixed(1)} MB`;}
export function ConversationPanel({role,supabaseConfigured}:{role:"justin"|"chloe";supabaseConfigured:boolean}){
  const[conversation,setConversation]=useState<ConversationView|null>(null),[body,setBody]=useState(""),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[context,setContext]=useState<{id:string;title:string}|null>(null);const fileInput=useRef<HTMLInputElement|null>(null),end=useRef<HTMLDivElement|null>(null);
  const headers=useCallback(():Record<string,string>=>supabaseConfigured?{}:{"x-demo-user":role},[role,supabaseConfigured]);
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/conversations",{headers:headers()});const data=await response.json();if(!response.ok)throw new Error(data.error);setConversation(data.conversation);setError(null);}catch(reason){setError(reason instanceof Error?reason.message:"Messages could not be loaded.");setConversation(null);}finally{setLoading(false);}},[headers]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<{id:string;title:string}>).detail;setContext(detail);document.getElementById("conversation-composer")?.scrollIntoView({behavior:"smooth",block:"center"});};window.addEventListener("kairos:discuss-meeting",handler);return()=>window.removeEventListener("kairos:discuss-meeting",handler);},[]);
  useEffect(()=>{if(!supabaseConfigured)return;const client=createBrowserSupabaseClient(),channel=client.channel("direct-inbox").on("postgres_changes",{event:"*",schema:"public",table:"conversation_messages"},()=>load()).on("postgres_changes",{event:"*",schema:"public",table:"message_attachments"},()=>load()).subscribe();return()=>{void client.removeChannel(channel);};},[load,supabaseConfigured]);
  useEffect(()=>{end.current?.scrollIntoView({block:"nearest"});},[conversation?.messages.length]);
  async function send(){if(!conversation||(!body.trim()&&!file))return;setBusy(true);setError(null);try{const nonce=crypto.randomUUID();let response:Response;if(file){const form=new FormData();form.set("file",file);form.set("body",body.trim()||`Shared ${file.name}`);form.set("clientNonce",nonce);if(context)form.set("relatedMeetingId",context.id);response=await fetch(`/api/conversations/${conversation.id}/attachments`,{method:"POST",headers:headers(),body:form});}else response=await fetch(`/api/conversations/${conversation.id}/messages`,{method:"POST",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({body,clientNonce:nonce,relatedMeetingId:context?.id??null})});const data=await response.json();if(!response.ok)throw new Error(data.error);setBody("");setFile(null);setContext(null);if(fileInput.current)fileInput.current.value="";await load();}catch(reason){setError(reason instanceof Error?reason.message:"Message could not be sent.");}finally{setBusy(false);}}
  return <section className="card overflow-hidden" aria-label="Direct conversation"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--outline)] p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[var(--cyan-soft)] text-[var(--navy)]"><MessageCircle className="size-5"/></span><div><p className="eyebrow">Direct conversation</p><h2 className="font-display mt-1 text-xl font-semibold text-[var(--navy)]">{conversation?`Chat with ${conversation.otherUser.name}`:"Messages"}</h2></div></div><span className="inline-flex items-center gap-1 rounded-full bg-[#d5f6eb] px-3 py-1.5 text-xs font-bold text-[#075e49]"><Wifi className="size-3"/>{supabaseConfigured?"Realtime":"Live preview"}</span></header>
    <div className="max-h-[32rem] min-h-72 overflow-y-auto bg-[var(--surface-low)] p-4 sm:p-5" aria-live="polite">{loading&&!conversation?<div role="status" className="grid min-h-56 place-items-center"><LoaderCircle className="animate-spin text-[var(--cyan-deep)]"/></div>:conversation?.messages.length?conversation.messages.map((message)=><article key={message.id} className={`mb-3 flex ${message.senderKind==="system"?"justify-center":message.isMine?"justify-end":"justify-start"}`}>{message.senderKind==="system"?<div className={`w-full max-w-2xl rounded-xl border p-3 text-sm ${message.type==="system_lateness"?"border-[var(--gold)]/40 bg-[var(--gold-soft)] text-[var(--gold-deep)]":"border-[var(--cyan-deep)]/20 bg-[var(--cyan-soft)] text-[var(--cyan-deep)]"}`}><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide"><Bot className="size-4"/>Kairos · Automated{message.private&&<span className="ml-auto inline-flex items-center gap-1 normal-case tracking-normal"><LockKeyhole className="size-3"/>Private</span>}</div><p className="mt-2 text-[var(--ink)]">{message.body}</p>{message.relatedMeetingId&&<span className="mt-2 inline-flex rounded-full bg-white/75 px-2 py-1 text-[10px] font-bold">Meeting update</span>}</div>:<div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm shadow-sm ${message.isMine?"rounded-br-md bg-[var(--navy-container)] text-white":"rounded-bl-md border border-[var(--outline)] bg-white text-[var(--ink)]"}`}><p className={`text-[10px] font-bold uppercase tracking-wide ${message.isMine?"text-white/60":"text-[var(--muted)]"}`}>{message.senderName}</p><p className="mt-1 whitespace-pre-wrap">{message.body}</p>{message.relatedMeetingId&&<span className={`mt-2 inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${message.isMine?"bg-white/15":"bg-[var(--cyan-soft)] text-[var(--cyan-deep)]"}`}>Discussing meeting request</span>}{message.attachments.map((attachment)=><a key={attachment.id} href={attachment.downloadPath} target="_blank" rel="noreferrer" className={`mt-3 flex items-center gap-2 rounded-xl p-2.5 ${message.isMine?"bg-white/10":"bg-[var(--surface-low)]"}`}><FileText className="size-4 shrink-0"/><span className="min-w-0 flex-1"><strong className="block truncate text-xs">{attachment.name}</strong><span className="text-[10px] opacity-70">{size(attachment.sizeBytes)} · {attachment.previewable?"Preview or download":"Download"}</span></span><Download className="size-4"/></a>)}<time className={`mt-2 block text-right text-[10px] ${message.isMine?"text-white/55":"text-[var(--muted)]"}`}>{clock(message.createdAt)}</time></div>}</article>):<div className="grid min-h-56 place-items-center text-center text-sm text-[var(--muted)]">Start a private conversation.</div>}<div ref={end}/></div>
    {error&&<div role="alert" className="flex gap-2 border-t border-[#ffb4ab] bg-[#ffdad6] p-3 text-sm text-[#93000a]"><AlertCircle className="size-4 shrink-0"/>{error}</div>}
    <div id="conversation-composer" className="border-t border-[var(--outline)] p-4">{context&&<div className="mb-3 flex items-center justify-between rounded-xl bg-[var(--cyan-soft)] px-3 py-2 text-xs text-[var(--cyan-deep)]"><span>Discussing: <strong>{context.title}</strong></span><button onClick={()=>setContext(null)} className="font-bold">Clear</button></div>}{file&&<div className="mb-3 flex items-center justify-between rounded-xl bg-[var(--surface-low)] px-3 py-2 text-xs"><span className="truncate">{file.name} · {size(file.size)}</span><button onClick={()=>{setFile(null);if(fileInput.current)fileInput.current.value="";}} className="font-bold text-[var(--error)]">Remove</button></div>}<div className="flex items-end gap-2 rounded-2xl border border-[var(--outline)] bg-white p-2 focus-within:border-[var(--cyan-deep)]"><label className="grid size-11 shrink-0 cursor-pointer place-items-center rounded-xl text-[var(--navy)] hover:bg-[var(--surface-low)]" title="Attach a file up to 10 MB"><Paperclip className="size-5"/><span className="sr-only">Attach file</span><input ref={fileInput} type="file" className="sr-only" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,application/pdf,image/png,image/jpeg,image/webp,text/plain" onChange={(event)=>setFile(event.target.files?.[0]??null)}/></label><textarea aria-label="Write a message" value={body} onChange={(event)=>setBody(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send();}}} rows={2} maxLength={4000} placeholder={`Message ${conversation?.otherUser.name??"your connection"}`} className="max-h-32 min-h-11 flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none"/><button aria-label="Send message" disabled={busy||(!body.trim()&&!file)} onClick={()=>void send()} className="grid size-11 shrink-0 place-items-center rounded-xl bg-[var(--navy)] text-white disabled:opacity-40">{busy?<LoaderCircle className="size-4 animate-spin"/>:<Send className="size-4"/>}</button></div><p className="mt-2 text-[11px] text-[var(--muted)]">PDF, images, WebP, or text · 10 MB maximum · links expire after 60 seconds</p></div>
  </section>;
}
