do $$ begin create type public.meeting_state as enum('draft','options_sent','awaiting_sender_confirmation','confirmed','declined','expired','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.connection_state as enum('pending','accepted','blocked'); exception when duplicate_object then null; end $$;

create table if not exists public.connections(
  id uuid primary key default gen_random_uuid(),requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,status public.connection_state not null default 'pending',created_at timestamptz not null default now(),
  constraint connection_not_self check(requester_id<>addressee_id),unique(requester_id,addressee_id)
);
create table if not exists public.schedule_permissions(
  owner_id uuid not null references public.profiles(id) on delete cascade,grantee_id uuid not null references public.profiles(id) on delete cascade,
  scope text not null default 'free_busy' check(scope in('none','free_busy')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,grantee_id)
);
create table if not exists public.meeting_requests(
  id uuid primary key default gen_random_uuid(),created_by uuid not null references public.profiles(id) on delete cascade,title text not null check(char_length(title) between 1 and 160),
  duration_minutes integer not null check(duration_minutes between 15 and 480),range_start timestamptz not null,range_end timestamptz not null,timezone text not null,
  state public.meeting_state not null default 'draft',selected_option_id uuid,active_responder uuid references public.profiles(id) on delete set null,version integer not null default 1,base_schedule_versions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint meeting_range_valid check(range_end>range_start)
);
create table if not exists public.meeting_participants(
  meeting_id uuid not null references public.meeting_requests(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,email text,name text not null,
  role text not null check(role in('organizer','recipient')),created_at timestamptz not null default now(),
  constraint participant_identity check((user_id is not null)::integer+(email is not null)::integer=1),unique(meeting_id,user_id),unique(meeting_id,email)
);
create table if not exists public.meeting_options(
  id uuid primary key default gen_random_uuid(),meeting_id uuid not null references public.meeting_requests(id) on delete cascade,start_at timestamptz not null,end_at timestamptz not null,
  label text not null,reason text not null,source text not null check(source in('kairos','counter')),created_by uuid references public.profiles(id) on delete set null,version integer not null default 1,created_at timestamptz not null default now(),constraint option_range_valid check(end_at>start_at)
);
alter table public.meeting_requests drop constraint if exists meeting_requests_selected_option_id_fkey;
alter table public.meeting_requests add constraint meeting_requests_selected_option_id_fkey foreign key(selected_option_id) references public.meeting_options(id) on delete set null deferrable initially deferred;
create table if not exists public.meeting_transitions(
  id bigint generated by default as identity primary key,meeting_id uuid not null references public.meeting_requests(id) on delete cascade,from_state public.meeting_state,to_state public.meeting_state not null,
  actor_id uuid references public.profiles(id) on delete set null,version integer not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now()
);
create table if not exists public.external_booking_tokens(
  id uuid primary key default gen_random_uuid(),meeting_id uuid not null unique references public.meeting_requests(id) on delete cascade,token_hash text not null unique,
  expires_at timestamptz not null,revoked_at timestamptz,created_at timestamptz not null default now()
);
create table if not exists public.simulated_deliveries(
  id uuid primary key default gen_random_uuid(),meeting_id uuid not null references public.meeting_requests(id) on delete cascade,channel text not null check(channel in('email','sms')),
  destination_masked text not null,status text not null default 'simulated' check(status='simulated'),created_at timestamptz not null default now()
);

do $$ declare table_name text; begin foreach table_name in array array['connections','schedule_permissions','meeting_requests','meeting_participants','meeting_options','meeting_transitions','external_booking_tokens','simulated_deliveries'] loop execute format('alter table public.%I enable row level security',table_name);execute format('alter table public.%I force row level security',table_name);end loop;end $$;
create or replace function public.can_access_meeting(p_meeting_id uuid)returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.meeting_requests m where m.id=p_meeting_id and (m.created_by=auth.uid() or exists(select 1 from public.meeting_participants p where p.meeting_id=m.id and p.user_id=auth.uid()))) $$;
revoke all on function public.can_access_meeting(uuid) from public;grant execute on function public.can_access_meeting(uuid) to authenticated;
create policy connections_participants_select on public.connections for select to authenticated using(requester_id=(select auth.uid()) or addressee_id=(select auth.uid()));
create policy permissions_owner_or_grantee_select on public.schedule_permissions for select to authenticated using(owner_id=(select auth.uid()) or grantee_id=(select auth.uid()));
create policy meeting_requests_participant_select on public.meeting_requests for select to authenticated using(public.can_access_meeting(id));
create policy meeting_participants_own_select on public.meeting_participants for select to authenticated using(public.can_access_meeting(meeting_id));
create policy meeting_options_participant_select on public.meeting_options for select to authenticated using(public.can_access_meeting(meeting_id));
create policy meeting_transitions_participant_select on public.meeting_transitions for select to authenticated using(public.can_access_meeting(meeting_id));
create policy deliveries_organizer_select on public.simulated_deliveries for select to authenticated using(exists(select 1 from public.meeting_requests m where m.id=meeting_id and m.created_by=(select auth.uid())));
revoke all on public.connections,public.schedule_permissions,public.meeting_requests,public.meeting_participants,public.meeting_options,public.meeting_transitions,public.external_booking_tokens,public.simulated_deliveries from anon,authenticated;
grant select on public.connections,public.schedule_permissions,public.meeting_requests,public.meeting_participants,public.meeting_options,public.meeting_transitions,public.simulated_deliveries to authenticated;

create or replace function public.create_meeting_request(p_title text,p_duration integer,p_range_start timestamptz,p_range_end timestamptz,p_timezone text,p_recipient_user uuid,p_recipient_email text,p_recipient_name text,p_send boolean,p_options jsonb,p_token_hash text default null,p_token_expires timestamptz default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();meeting_id uuid;option jsonb;recipient_name text;recipient_email text;recipient_active uuid;base_versions jsonb;initial_state public.meeting_state:=case when p_send then 'options_sent'::public.meeting_state else 'draft'::public.meeting_state end;
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  if p_duration not between 15 and 480 or p_range_end<=p_range_start or jsonb_array_length(p_options) not between 1 and 5 then raise exception 'Invalid meeting request';end if;
  if p_recipient_user is not null then
    if not exists(select 1 from public.connections where status='accepted' and ((requester_id=actor and addressee_id=p_recipient_user)or(requester_id=p_recipient_user and addressee_id=actor))) then raise exception 'Connection required' using errcode='42501';end if;
    if not exists(select 1 from public.schedule_permissions where owner_id=p_recipient_user and grantee_id=actor and scope='free_busy') then raise exception 'Free busy permission required' using errcode='42501';end if;
    select full_name,email into recipient_name,recipient_email from public.profiles where id=p_recipient_user;
    recipient_active:=case when p_send then p_recipient_user else actor end;
  else
    if p_recipient_email is null or p_token_hash is null or p_token_expires<=now() then raise exception 'External recipient requires an expiring token';end if;
    recipient_name:=p_recipient_name;recipient_email:=p_recipient_email;recipient_active:=case when p_send then null else actor end;
  end if;
  base_versions:=jsonb_build_object(actor::text,(select schedule_version from public.profiles where id=actor));
  if p_recipient_user is not null then base_versions:=base_versions||jsonb_build_object(p_recipient_user::text,(select schedule_version from public.profiles where id=p_recipient_user));end if;
  insert into public.meeting_requests(created_by,title,duration_minutes,range_start,range_end,timezone,state,active_responder,base_schedule_versions)values(actor,p_title,p_duration,p_range_start,p_range_end,p_timezone,initial_state,recipient_active,base_versions)returning id into meeting_id;
  insert into public.meeting_participants(meeting_id,user_id,name,role)select meeting_id,actor,full_name,'organizer' from public.profiles where id=actor;
  insert into public.meeting_participants(meeting_id,user_id,email,name,role)values(meeting_id,p_recipient_user,case when p_recipient_user is null then recipient_email end,recipient_name,'recipient');
  for option in select value from jsonb_array_elements(p_options) loop insert into public.meeting_options(id,meeting_id,start_at,end_at,label,reason,source,created_by)values((option->>'id')::uuid,meeting_id,(option->>'startAt')::timestamptz,(option->>'endAt')::timestamptz,option->>'label',option->>'reason','kairos',actor);end loop;
  if p_recipient_user is null then insert into public.external_booking_tokens(meeting_id,token_hash,expires_at)values(meeting_id,p_token_hash,p_token_expires);if p_send then insert into public.simulated_deliveries(meeting_id,channel,destination_masked)values(meeting_id,'email','***@'||split_part(recipient_email,'@',2));end if;end if;
  insert into public.meeting_transitions(meeting_id,to_state,actor_id,version)values(meeting_id,initial_state,actor,1);return meeting_id;
end $$;
revoke all on function public.create_meeting_request(text,integer,timestamptz,timestamptz,text,uuid,text,text,boolean,jsonb,text,timestamptz) from public;grant execute on function public.create_meeting_request(text,integer,timestamptz,timestamptz,text,uuid,text,text,boolean,jsonb,text,timestamptz) to authenticated;

create or replace function public.respond_to_meeting(p_meeting_id uuid,p_action text,p_option_id uuid default null,p_counter_start timestamptz default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();meeting public.meeting_requests%rowtype;role_name text;old_state public.meeting_state;recipient_id uuid;chosen public.meeting_options%rowtype;counter_id uuid;
begin
  if actor is null then raise exception 'Authentication required' using errcode='42501';end if;
  select * into meeting from public.meeting_requests where id=p_meeting_id for update;if not found then raise exception 'Meeting not found' using errcode='42501';end if;
  select role into role_name from public.meeting_participants where meeting_id=p_meeting_id and user_id=actor;if role_name is null then raise exception 'Not a participant' using errcode='42501';end if;
  if meeting.state in('confirmed','declined','expired','cancelled') then raise exception 'Meeting already closed';end if;old_state:=meeting.state;
  if p_action='send' and role_name='organizer' and meeting.state='draft' then select user_id into recipient_id from public.meeting_participants where meeting_id=p_meeting_id and role='recipient';update public.meeting_requests set state='options_sent',active_responder=recipient_id,version=version+1,updated_at=now() where id=p_meeting_id;
  elsif p_action='accept' and role_name='recipient' and meeting.state='options_sent' then if not exists(select 1 from public.meeting_options where id=p_option_id and meeting_id=p_meeting_id)then raise exception 'Invalid option';end if;update public.meeting_requests set state='awaiting_sender_confirmation',selected_option_id=p_option_id,active_responder=created_by,version=version+1,updated_at=now()where id=p_meeting_id;
  elsif p_action='counter' and role_name='recipient' and meeting.state='options_sent' then if p_counter_start is null or p_counter_start<meeting.range_start or p_counter_start+make_interval(mins=>meeting.duration_minutes)>meeting.range_end then raise exception 'Counter outside range';end if;insert into public.meeting_options(meeting_id,start_at,end_at,label,reason,source,created_by)values(p_meeting_id,p_counter_start,p_counter_start+make_interval(mins=>meeting.duration_minutes),to_char(p_counter_start at time zone meeting.timezone,'Dy, FMHH12:MI AM'),'Recipient counteroffer','counter',actor)returning id into counter_id;update public.meeting_requests set state='awaiting_sender_confirmation',selected_option_id=counter_id,active_responder=created_by,version=version+1,updated_at=now()where id=p_meeting_id;
  elsif p_action='decline' and role_name='recipient' and meeting.state='options_sent' then update public.meeting_requests set state='declined',active_responder=null,version=version+1,updated_at=now()where id=p_meeting_id;
  elsif p_action='cancel' and role_name='organizer' then update public.meeting_requests set state='cancelled',active_responder=null,version=version+1,updated_at=now()where id=p_meeting_id;
  elsif p_action='confirm' and role_name='organizer' and meeting.state='awaiting_sender_confirmation' then
    select * into chosen from public.meeting_options where id=meeting.selected_option_id and meeting_id=p_meeting_id;if not found then raise exception 'Selected option missing';end if;
    if exists(select 1 from public.meeting_participants participant join public.profiles profile on profile.id=participant.user_id where participant.meeting_id=p_meeting_id and profile.schedule_version<>coalesce((meeting.base_schedule_versions->>(participant.user_id::text))::integer,-1))then raise exception 'Participant schedule changed' using errcode='40001';end if;
    if exists(select 1 from public.meeting_participants participant join public.calendar_items item on item.user_id=participant.user_id where participant.meeting_id=p_meeting_id and item.status='scheduled' and item.start_at<chosen.end_at and item.end_at>chosen.start_at)then raise exception 'Participant schedule changed' using errcode='40001';end if;
    insert into public.calendar_items(user_id,item_type,title,description,start_at,end_at,timezone,priority,flexibility,normal_duration_minutes,minimum_duration_minutes,category,source_proposal_id)
      select participant.user_id,'event',meeting.title,'Confirmed through Kairos',chosen.start_at,chosen.end_at,meeting.timezone,4,'fixed',meeting.duration_minutes,meeting.duration_minutes,'Meeting',null from public.meeting_participants participant where participant.meeting_id=p_meeting_id and participant.user_id is not null;
    update public.profiles set schedule_version=schedule_version+1 where id in(select user_id from public.meeting_participants where meeting_id=p_meeting_id and user_id is not null);
    update public.meeting_requests set state='confirmed',active_responder=null,version=version+1,updated_at=now()where id=p_meeting_id;
  else raise exception 'Invalid meeting transition';end if;
  select * into meeting from public.meeting_requests where id=p_meeting_id;insert into public.meeting_transitions(meeting_id,from_state,to_state,actor_id,version,metadata)values(p_meeting_id,old_state,meeting.state,actor,meeting.version,jsonb_build_object('action',p_action));return jsonb_build_object('meeting_id',p_meeting_id,'state',meeting.state,'version',meeting.version);
end $$;
revoke all on function public.respond_to_meeting(uuid,text,uuid,timestamptz) from public;grant execute on function public.respond_to_meeting(uuid,text,uuid,timestamptz) to authenticated;

create or replace function public.respond_to_external_booking(p_token_hash text,p_action text,p_option_id uuid default null,p_counter_start timestamptz default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare token_record public.external_booking_tokens%rowtype;meeting public.meeting_requests%rowtype;counter_id uuid;old_state public.meeting_state;
begin
  select * into token_record from public.external_booking_tokens where token_hash=p_token_hash for update;
  if not found or token_record.revoked_at is not null or token_record.expires_at<=now() then raise exception 'Booking token invalid or expired' using errcode='42501';end if;
  select * into meeting from public.meeting_requests where id=token_record.meeting_id for update;
  if meeting.state<>'options_sent' then raise exception 'Booking no longer awaiting response';end if;old_state:=meeting.state;
  if p_action='accept' then if not exists(select 1 from public.meeting_options where id=p_option_id and meeting_id=meeting.id)then raise exception 'Invalid option';end if;update public.meeting_requests set state='awaiting_sender_confirmation',selected_option_id=p_option_id,active_responder=created_by,version=version+1,updated_at=now()where id=meeting.id;
  elsif p_action='counter' then if p_counter_start is null or p_counter_start<meeting.range_start or p_counter_start+make_interval(mins=>meeting.duration_minutes)>meeting.range_end then raise exception 'Counter outside range';end if;insert into public.meeting_options(meeting_id,start_at,end_at,label,reason,source)values(meeting.id,p_counter_start,p_counter_start+make_interval(mins=>meeting.duration_minutes),to_char(p_counter_start at time zone meeting.timezone,'Dy, FMHH12:MI AM'),'Guest counteroffer','counter')returning id into counter_id;update public.meeting_requests set state='awaiting_sender_confirmation',selected_option_id=counter_id,active_responder=created_by,version=version+1,updated_at=now()where id=meeting.id;
  elsif p_action='decline' then update public.meeting_requests set state='declined',active_responder=null,version=version+1,updated_at=now()where id=meeting.id;
  else raise exception 'Invalid external response';end if;
  select * into meeting from public.meeting_requests where id=token_record.meeting_id;insert into public.meeting_transitions(meeting_id,from_state,to_state,version,metadata)values(meeting.id,old_state,meeting.state,meeting.version,jsonb_build_object('external',true,'action',p_action));return jsonb_build_object('meeting_id',meeting.id,'state',meeting.state,'version',meeting.version);
end $$;
revoke all on function public.respond_to_external_booking(text,text,uuid,timestamptz) from public;grant execute on function public.respond_to_external_booking(text,text,uuid,timestamptz) to service_role;

do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='meeting_requests')then alter publication supabase_realtime add table public.meeting_requests;end if;end $$;
